#!/bin/ksh
#=======================================================
# Driving script to check differences between nam or smartinit grib files
# Jeff McQueen   02/25/2013
#=======================================================
#set -x 
typeset -Z2 cyc ffhr

#===============================================================
# RUNTYP for GRID smart : conus ak hi pr conus2p5 ak3
# RUNTYP for GRID bsmart: conusnest, alaskanest,hawaiinest,priconest
# RUNTYP for GRID bgrd3d:
#===============================================================
export RUNTYP=conus
GRID=smart        #smart, bgrd3d, bsmart
mdl=nam

yymmdd=20140331
export cyc=06       

export ffhr=00     # Starting forecast hour
export ENDHRS=00   # Ending forecast hour
INCR=03            # Forecast hour increment
fhrstr=$ffhr       # hr to start comparisons

ioff=0
if [ $cyc -eq 06 -o $cyc -eq 18 ];then let ioff=6;fi

#===============================================================
# location of smartinit files
#===============================================================
ncodir=/com/${mdl}/prod/${mdl}.${yymmdd}  #CCS
# devdir=/ptmpp1/${USER}/smart${RUNTYP}/${mdl}.${yymmdd}     #EMC PARA 
devdir=/ptmpp1/${USER}/${mdl}.${yymmdd}     #EMC PARA 

#===============================================================
# GRIB1 FILE PREFIX NAME FORMAT (eg: nam.t12z.bgrd3d42.tm00)
#===============================================================
case $GRID in 
  bgrd3d)
    RUNTYP=;awprun=".";
    smpre=${mdl}.t${cyc}z.${GRID};;
  bsmart) 
    awprun=".${RUNTYP}"
    smpre=${mdl}.t${cyc}z.${RUNTYP}.${GRID};;
  smart)
    awprun=;  
    smpre=${mdl}.t${cyc}z.${GRID}${RUNTYP};;
esac

#### cd $devdir
set +x

#===============================================================
# Begin creating separate files and checking for differences
#===============================================================
while [ $ffhr -le $ENDHRS ];do
  rm -f dft1 dft2 dfp dfp12 dffull
  let fhrv12=$ffhr-$ioff
  ((ichk12=$fhrv12%12))
  ((ichk6=$ffhr%6))
  let fhr1=$ffhr-1;let fhr2=$ffhr-2;let fhr6=$ffhr-6;let fhr12=$ffhr-12
  echo;echo ==================================================================================
  echo DOMAIN $RUNTYP    CYCLE $cyc    FORECAST HOUR $ffhr

  ln -fs ${ncodir}/${smpre}${ffhr}.tm00 nco_file   
  ln -fs ${devdir}/${smpre}${ffhr}.tm00 dev_file  

  if [ ! -s nco_file ];then echo " nco_file ${ncodir} ${smpre}$ffhr.tm00 ${RUNTYP} not found";exit;fi
  if [ ! -s dev_file ];then echo " dev_file ${devdir} ${smpre}$ffhr.tm00 ${RUNTYP}not found";exit;fi
  ls -ltr nco_file
  ls -ltr dev_file
  let fhr=$ffhr

#===============================================================
# Check GRIB2 file differences
#===============================================================
  gb2file=${smpre}${ffhr}.tm00.grib2
  if [ ! -s ${ncodir}/$gb2file ];then
    echo;echo NCO $gb2file NOT FOUND
  elif [ ! -s ${devdir}/$gb2file ];then
    echo;echo DEV $gb2file NOT FOUND
  else
    diff  ${ncodir}/${gb2file} ${devdir}/${gb2file} >grib2-df
    if [ -s grib2-df ];then 
      echo; echo "WARNING : GRIB2 FILES DIFFER";echo
    else
      echo;echo "GRIB2 FILES ARE IDENTICAL";echo
    fi
  fi

#===============================================================
# Check awip file differences
#===============================================================
  if [ "$RUNTYP" = ak3 ];then awprun="3.ak";fi
  awpfile=grib2.awp${mdl}${GRID}${awprun}${ffhr}_awips_f${ffhr}_${cyc}
  if [ -s ../$awpfile ];then
    diff /pcom/${mdl}/$awpfile ../$awpfile >nawips-df
    if [ -s nawips-df ];then 
      echo; echo "WARNING : NAWIPS GRIB2 FILES DIFFER $awprun ";exit
    else
      echo "NAWIPS GRIB2 FILES ARE IDENTICAL"
    fi
  else
    echo $mdl AWIPS FILE  $awpfile NOT FOUND
    ls -ltr /pcom/${mdl}/$awpfile
  fi


#=====================================================================================
# Separate Temps, precip at different forecast hours, or ranges from full grib file
# WFLG=-v    : create full grib file without duplicate temps, precip
#     = null : create separate temperature and precip files
#=====================================================================================
  for WFLG in "null" "-v" ;do
    for gbfl in nco dev;do
      rm -f ${gbfl}-*
      INGB=${gbfl}_file
      wf=$WFLG

      if [ $WFLG = null ];then wf=;fi
      wgrib -s $INGB | grep $wf  ":sfc:${fhr1}hr " | wgrib -i -grib \
      $INGB -o ${gbfl}-temp   >/dev/null

      if [ $WFLG = null ];then 

#=====================================================================================
#     Create separate temps, 6 and 12 hr accum precip from full grib file
#=====================================================================================
        wgrib -s $INGB | grep ":sfc:${fhr2}hr " | wgrib -i -grib \
        $INGB -o ${gbfl}-temp2  >>wgrib.out 
        if [ ${ichk6} -eq 0 ];then
          wgrib -s $INGB | grep ":sfc:${fhr6}-${fhr}hr " | wgrib -i -grib \
          $INGB -o ${gbfl}-prcp  >>wgrib.out
        fi
        if [ $ichk12 -eq 0 ];then
          wgrib -s $INGB | grep ":sfc:${fhr12}-${fhr}hr " | wgrib -i -grib \
          $INGB -o ${gbfl}-prcp12  >>wgrib.out
        fi
      else

#=====================================================================================
#     Remove duplicate temps, 6 and 12 hour precip from full grib file
#=====================================================================================
        wgrib -s $gbfl-temp | grep $wf ":sfc:${fhr2}hr " | wgrib -i -grib \
          $gbfl-temp -o ${gbfl}-f2     >>wgrib.out
        wgrib -s $gbfl-f2 | grep $wf ":sfc:${fhr6}-${fhr}hr " | wgrib -i -grib \
          $gbfl-f2 -o ${gbfl}-f3  >>wgrib.out
        wgrib -s $gbfl-f3 | grep $wf ":sfc:${fhr12}-${fhr}hr " | wgrib -i -grib \
          $gbfl-f3 -o ${gbfl}-full  >>wgrib.out
      fi
    done
 
#=====================================================================================
#   Create difference files for full, previous hours temps and precip
#=====================================================================================
    if [ $WFLG = "null" ];then
      if [ -s nco-temp ];then diffgb -x nco-temp dev-temp >dft1;fi         #max temperature 
      if [ -s nco-temp2 ];then diffgb -x nco-temp2 dev-temp2 >dft2;fi      #min temperature
      if [ -s nco-prcp ];then diffgb -x nco-prcp dev-prcp >dfp;fi          #6hr accum prcp
      if [ -s nco-prcp12 ];then diffgb -x nco-prcp12 dev-prcp12 >dfp12;fi  #12hr accum precip
    else
      diffgb -x nco-full dev-full >dffull
    fi
  done

#=====================================================================================
# Print any differences between files 
#=====================================================================================
  echo;head -n 3 dffull;echo
  for DFL in dffull dft1 dft2 dfp dfp12;do  
    if [ -s $DFL ];then
      let maxlines=`wc $DFL |awk '{print $1 }'`;let maxlines=$maxlines-2
      case $RUNTYP in 
        conus2p5|ak3 ) set -A ndiff `cat $DFL | awk '{ print $9 }'`;;
           conusnest ) set -A ndiff `cat $DFL | awk '{ print $10 }'`;;
                    *) set -A ndiff `cat $DFL | awk '{ print $13 }'`;;
      esac 
      let il=4
      ldiff=0
      while [ $il -lt $maxlines ];do
        if [ ${ndiff[il]} -gt 0 ];then 
          if [ $ldiff -eq 0 ];then
            echo;echo  $DFL FILES ARE DIFFERENT
            more +4 $DFL |head -1
          fi
          let iln=il+2
          more +${iln} $DFL |head -1
          ldiff=1
        fi
        let il=il+1
      done
      if [ $ldiff -eq 0 -a -s $DFL ];then echo "$DFL FILES ARE IDENTICAL";fi
    fi
  done
  echo
  let ffhr=$ffhr+$INCR 
done

rm -f nco-prcp* nco-temp* nco-f* 
rm -f dev-prcp* dev-temp* dev-f*
