#!/bin/ksh
#================================================================================
#  Create Bjob header
#================================================================================
typeset -Z2 jfhr
job=$1
jfhr=$2
# Create J{MDL}_SMINIT job
  echo "#BSUB -J ${job}"             >bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -oo /ptmpp2/${USER}/${modeld}.${model_ver}/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -eo /ptmpp2/${USER}/${modeld}.${model_ver}/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -n 1"                >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -W ${WALLCLK}"       >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -P RTMA-T2O"             >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -q dev2_shared"              >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -R affinity[core]"    >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -R "rusage[mem=10000]"" >>bjobcards-dev${RUNTYP}-$jfhr
 
#cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT.test  > J${MDL}_SMINIT.${RUNTYP}
cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT  > J${MDL}_SMINIT.${RUNTYP}
rm -f bjobcards-dev${RUNTYP}-$jfhr
