#!/bin/ksh
#================================================================================
#  Create Bjob header
#================================================================================
typeset -Z2 jfhr
job=$1
jfhr=$2
# Create J{MDL}_SMINIT job
  echo "#BSUB -J ${job}"             >bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -oo /stmpp2/${USER}/${modeld}.${nam_smartinit_ver}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -eo /stmpp2/${USER}/${modeld}.${nam_smartinit_ver}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -n 12"                >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -W ${WALLCLK}"       >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -P RTMA-T2O"             >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -q dev2"              >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -R "span[ptile=12]""    >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -R affinity[core(1)]"    >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -R "rusage[mem=3500]"" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#BSUB -a poe"                       >>bjobcards-dev${RUNTYP}-$jfhr
 
#cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT.test  > J${MDL}_SMINIT.${RUNTYP}
cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT  > J${MDL}_SMINIT.${RUNTYP}
rm -f bjobcards-dev${RUNTYP}-$jfhr
