#!/bin/ksh
#================================================================================
#  Create Bjob header
#================================================================================
typeset -Z2 jfhr
job=$1
jfhr=$2
# Create J{MDL}_SMINIT job
  echo "#PBS -N ${job}"             >bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -o /lfs/h1/emc/ptmp/${USER}/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -e /lfs/h1/emc/ptmp/${USER}/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -l select=1:ncpus=24"                >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -l walltime=${WALLCLK}"       >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -A project"             >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -q workq"              >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -V"              >>bjobcards-dev${RUNTYP}-$jfhr

# echo "source /apps/prod/lmodules/startLmod"     >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module purge" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load intel/19.1.3.304 PrgEnv-intel" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load intel/19.1.3.304/cray-mpich/8.1.4" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load cray-pals/1.0.8"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load envvar/1.0"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load prod_util/2.0.2"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load prod_envir/2.0.2"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load grib_util/1.2.2"               >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/src/v1.1.0/install2/modulefiles/stack" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load hpc" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load hpc-intel" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load hpc-cray-mpich" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load wgrib2/2.0.8ip" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load cce/11.0.2" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load git/2.29.0" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load gcc/10.2.0" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load intel/19.1.3.304" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load libjpeg/9c" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module use /lfs/h1/emc/nceplibs/noscrub/hpc-stack/test/v1.1.0/modulefiles/stack" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load hpc" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load hpc-intel" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load hpc-cray-mpich" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load grib_util/1.2.2" >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load envvar/1.0"                      >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load prod_util/2.0.2"                      >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load prod_envir/2.0.2"                      >>bjobcards-dev${RUNTYP}-$jfhr
# echo "module load grib_util/1.2.2"               >>bjobcards-dev${RUNTYP}-$jfhr

#cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT.test  > J${MDL}_SMINIT.${RUNTYP}
cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}_SMINIT  > J${MDL}_SMINIT.${RUNTYP}
rm -f bjobcards-dev${RUNTYP}-$jfhr
