#!/bin/ksh
#================================================================================
#  Create Bjob header
#================================================================================
typeset -Z2 jfhr
job=$1
jfhr=$2
# Create J{MDL}_SMINIT job
  echo "#PBS -N ${job}"             >bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -o /lfs/h2/emc/ptmp/${USER}/${modeld}.${rrfs_smartinit_ver}_test/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -e /lfs/h2/emc/ptmp/${USER}/${modeld}.${rrfs_smartinit_ver}_test/${PDY}/${cyc}/list/o${job}" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -l place=shared,select=1:ncpus=12:mpiprocs=12:mem=32GB"    >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -l walltime=${WALLCLK}"       >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -A RTMA-DEV"             >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -q dev"              >>bjobcards-dev${RUNTYP}-$jfhr
# echo "#PBS -l debug=true"              >>bjobcards-dev${RUNTYP}-$jfhr
  echo "#PBS -V"              >>bjobcards-dev${RUNTYP}-$jfhr

  echo "module purge" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load envvar/1.0" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load PrgEnv-intel/8.1.0" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load craype/2.7.8" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load intel/19.1.3.304" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load cray-mpich/8.1.7"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load cray-pals/1.0.12"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load prod_util/2.0.9"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load prod_envir/2.0.4"                      >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load libjpeg/9c"               >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load grib_util/1.2.2"               >>bjobcards-dev${RUNTYP}-$jfhr
  echo "module load wgrib2/2.0.8_wmo" >>bjobcards-dev${RUNTYP}-$jfhr
  echo "export  OMP_NUM_THREADS=1" >>bjobcards-dev${RUNTYP}-$jfhr

cat bjobcards-dev${RUNTYP}-$jfhr  ${jobd}/J${MDL}  > J${MDL}.${RUNTYP}
rm -f bjobcards-dev${RUNTYP}-$jfhr
