#!/bin/ksh

set -x

#==========================================
# Submit several smartinit domain runs
# calls RUN_ALL which submits each RUNTYP domain JNAM_SMINIT job
# Viable RUNTYP=conus,conusnest2p5,ak,ak_rtmages,aknest3,hi,pr,guamnmmb, guamarw
# Jeff McQueen
# 
#   Jun 2015 Annette Gibbs - Changed smartinit to run on phase 2
# 7 Jul 2015 Annette Gibbs - Changed smartinit output from /ptmpp2/$USER to /meso2/noscrub/$USER
# 7 Jul 2015 Annette Gibbs - Changed smartinit output from /stmpp2/$USER to /ptmpp2/$USER and added $PDY to dir
# 7 Jul 2015 Annette Gibbs - $PDY is now determined in DRIVcs2p and DRIV-dgex
#==========================================

# set job directory needed if running from cron
export rrfs_smartinit_ver=v5.0.0
export smartinit_ver=v5.0
export code_ver=v5.0.0
export modeld=smartinit
export rootd=/lfs/h2/emc/da/save/${USER}/packages/${modeld}.${rrfs_smartinit_ver}_test
echo $rootd
export RUN_ENVIR=emc
export envir=emc

export jobd=${rootd}/jobs
export kickd=${rootd}/kick-scripts

cd $kickd

# Determine date
export PDY=`$NDATE |cut -c 1-8`
export PDY=20251017 ###TEST

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 07 ];then export cyc=00;
elif [ $HH -le 13 ];then export cyc=06;
elif [ $HH -le 19 ];then export cyc=12;
else 
  export cyc=18
fi 
export cyc=06  #TEST

export fhrstr=0
export INCR=03
echo DRIVER $modeld run CYC $cyc fhr $fhrstr 

#====================================================================
domains="priconest aknest3 conusnest2p5 hawaiinest"
#====================================================================
for RUNTYP in $domains ;do
  export mdl=rrfs
  case  $RUNTYP in priconest|hawaiinest) export ENDHRS=84;; 
                                aknest3) export ENDHRS=60;; 
                           conusnest2p5) export ENDHRS=60;; 
  esac

  export NET=smartinit
  export RUN=$mdl
  export RUNTYP=$RUNTYP

# Remove older directories
  dayrm=$( echo `$NDATE -120` |cut -c 1-8 )

  Y=$(echo $dayrm | cut  -c 1-4 )
  M=$(echo $dayrm | cut  -c 5-6 )
  D=$(echo $dayrm | cut  -c 7-8 )
  wdayd=$Y$M$D
# rm -rf /gpfs/dell2/ptmp/${USER}/${code_ver}/${mdl}.${wdayd}
# rm /gpfs/dell2/ptmp/${USER}/${code_ver}/jlogfile.${wdayd}
# rm -r /gpfs/dell2/ptmp/${USER}/${modeld}.${rrfs_smartinit_ver}/${wdayd}

# Create and submit JNAM_SMINIT job

  echo `date +%T` SUBMIT RUN_ALL $RUNTYP  CYC $cyc from $fhrstr to $ENDHRS
  mkdir -p /lfs/h2/emc/ptmp/${USER}/${modeld}.${rrfs_smartinit_ver}_test/${PDY}/${cyc}
  mkdir -p /lfs/h2/emc/ptmp/${USER}/${modeld}.${rrfs_smartinit_ver}_test/${PDY}/${cyc}/list
  ${kickd}/RUN_ALL >/lfs/h2/emc/ptmp/$USER/${modeld}.${rrfs_smartinit_ver}_test/${PDY}/${cyc}/list/RUNout${modeld}-${RUNTYP}${cyc} 2>&1 &
  sleep 10
done
