#!/bin/ksh
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/default/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils
#module load prod_util
#module load /nwpara2/modulefiles/util_shared/v1.0.3 

#==========================================
# Submit several nam_smartinit domain runs
# calls RUN_ALL which submits each RUNTYP domain JNAM_SMINIT job
# Viable RUNTYP=conus,conusnest2p5,ak,ak_rtmages,aknest3,hi,pr,guamnmmb, guamarw
# Jeff McQueen
# 
#   Jun 2015 Annette Gibbs - Changed smartinit to run on phase 2
# 7 Jul 2015 Annette Gibbs - Changed smartinit output from /ptmpp2/$USER to /meso2/noscrub/$USER
# 7 Jul 2015 Annette Gibbs - Changed smartinit output from /stmpp2/$USER to /ptmpp2/$USER and added $PDY to dir
# 7 Jul 2015 Annette Gibbs - $PDY is now determined in DRIVcs2p and DRIV-dgex
#==========================================

# set job directory needed if running from cron
#export model_ver=v3.5.1
export nam_smartinit_ver=v5.0.0
export code_ver=v5.0.0
export which_nam=prod
export modeld=smartinit
export rootd=/meso/save/${USER}/${modeld}.${nam_smartinit_ver}
export RUN_ENVIR=emc
export envir=emc

export jobd=${rootd}/jobs
export kickd=${rootd}/kick-scripts

cd $kickd

# Determine date
  export PDY=`/nwprod/util/exec/ndate |cut -c 1-8`
#export PDY=20170817 ###TEST
#export PDY=20170907 ###TEST
#export PDY=20170911 ###TEST

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 07 ];then export cyc=00;
elif [ $HH -le 13 ];then export cyc=06;
elif [ $HH -le 19 ];then export cyc=12;
else 
  export cyc=18
fi 
export cyc=00  #TEST
domhrw=;
#TEST case $cyc in 00|12) domhrw="guamnmmb guamarw";;esac

export fhrstr=0
export INCR=03
echo DRIVER $modeld run CYC $cyc fhr $fhrstr 

#07/13: change to run ak and alaskanest separately for good output listing
#07/13: added guamnmmb,guamarw  configuration
#07/13: changed so 00 hr comes from parent nam for conus,ak,hi,pr (ecf scripts file)
#domains="conusnest2p5  hi ak pr conus aknest3 ak_rtmages"

#====================================================================
#domains="pr aknest3 ak_rtmages conusnest2p5 hi"
#domains="priconest aknest3 conusnest2p5 hawaiinest"
domains="priconest"
#domains="conusnest2p5 aknest3"
#domains="aknest3"
#domains="conusnest2p5"
#domains="priconest hawaiinest"
#domains="priconest"
#domains="hawaiinest"
#domains="conusnest2p5  hi ak conus aknest3 ak_rtmages"
#domains="ak_rtmages"
#domains="conusnest2p5 aknest3"
#domains="conus"
#domains="ak"
#domains="aknest3 ak_rtmages"
#domains="aknest3 conusnest2p5"
#domains="hi pr"
#domains="pr"
#domains="pr aknest3 conusnest2p5"
#domains="hi pr aknest3 "
#domains="conusnest2p5 pr hi"
#====================================================================

for RUNTYP in $domains  $domhrw $domdgx ;do
  export ENDHRS=03
 export mdl=nam
#  export mdl=namrr
  case  $RUNTYP in guamarw|guamnmmb) export ENDHRS=12;export mdl=hiresw;; 
                         ak_rtmages) ENDHRS=12;;
                            aknest3) export ENDHRS=03;; 
                       conusnest2p5) export ENDHRS=03;; 
                       dgex) export fhrstr=87; export ENDHRS=192;; 
  esac

# Hourly forecasts to 18-h for the parent 12 km, 3 km DONUS nest and 3km Alaska
   if [ $cyc -ne 00 -a $cyc -ne 06 -a $cyc -ne 12 -a $cyc -ne 18 ];then export ENDHRS=18;fi 

  export NET=$mdl
  export RUN=$NET
  export RUNTYP=$RUNTYP

# Remove older directories
  /nwprod/util/ush/setpdy.sh
  dayrm=$( echo `/nwprod/util/exec/ndate -120` |cut -c 1-8 )

  Y=$(echo $dayrm | cut  -c 1-4 )
  M=$(echo $dayrm | cut  -c 5-6 )
  D=$(echo $dayrm | cut  -c 7-8 )
  wdayd=$Y$M$D
  rm -rf /meso2/noscrub/${USER}/${code_ver}/${mdl}.${wdayd}
  rm -rf /meso2/noscrub/${USER}/figs/dng_para/${wdayd}${cyc}
  rm -rf /meso2/noscrub/${USER}/figs/dng_rtma/${wdayd}${cyc}
  rm /meso2/noscrub/${USER}/${code_ver}/jlogfile.${wdayd}
  rm -r /ptmpp2/${USER}/${modeld}.${nam_smartinit_ver}/${wdayd}

# Create and submit JNAM_SMINIT job

  echo `date +%T` SUBMIT RUN_ALL $RUNTYP  CYC $cyc from $fhrstr to $ENDHRS
  mkdir -p /ptmpp2/${USER}/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}
  mkdir -p /ptmpp2/${USER}/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}/list
  ${kickd}/RUN_ALL >/ptmpp2/$USER/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}/list/RUNout${modeld}-${RUNTYP}${cyc} 2>&1 &
  sleep 10
done
