#!/bin/ksh
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

#=======================================================
# Driving script to run a smartinit domain
# Called by DRIVER
# Submits JNAM_SMINIT.${RUNTYP}
# RUNTYP : conus ak alaskanest hi pr conusnest2p5 aknest3
#
# Uses ${cfgdir}/smart_para_config --> directory config
# Jeff McQueen       01/29/2013
# Vertical structure 08/27/2013
#=======================================================
#set -x 
typeset -Z2 cyc ffhr

#====================User Sets=======================================
# Location of smart config file to set up directories
cfgdir=${rootd}/parm
wkdir=${rootd}/working
gemdir=/meso/save/$USER/gempak/sfcplot/smart

export jobd=${jobd:-`pwd`}

# export RUNTYP=alaskanest # Set in DRIVER
# export cyc=12            # Set in DRIVER
#export fhrstr=00   # Starting forecast hour
#export ENDHRS=12   # Ending forecast hour
INCR=03            # Forecast hour increment

#  Input sub-directory for model to downscale (/com/nam/prod, com/hiresw/prod)
#  NCO should set NET and RUN before calling job

export NET=nam  
if [ $RUNTYP = guam ];then export NET=hiresw;fi

#================END User Sets=======================================

export ffhr=$fhrstr
while [ $ffhr -le $ENDHRS ];do
  export job="${modeld}.${RUNTYP}${cyc}-${ffhr}"
  rm -f /stmp/${USER}/${modeld}/list/o$job
  if [ $fhrstr -le 03 ];then 
    rm -rf /stmp/${USER}/${modeld}/$job
    mkdir -p /stmp/${USER}/${modeld}/$job
  fi
  cd /stmp/${USER}/${modeld}/${job}

# Create and invoke config file needed by Job 
  echo "export RUNTYP=$RUNTYP"   >$wkdir/dng_para_config${RUNTYP}
  echo "export cyc=$cyc"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export ffhr=$ffhr"      >>$wkdir/dng_para_config${RUNTYP}
  echo "export RM_TMPDIR=NO"    >>$wkdir/dng_para_config${RUNTYP}
  echo "export NET=$NET"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export RUN=$NET"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export mdl=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  cat $cfgdir/smart_para_config >>$wkdir/dng_para_config${RUNTYP}
  . ${wkdir}/dng_para_config${RUNTYP} 

# Create JNAM_SMINIT job
  echo "#BSUB -J ${job}"             >${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -oo /stmp/Jeff.McQueen/${modeld}/list/o${job}" >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -eo /stmp/Jeff.McQueen/${modeld}/list/o${job}" >>${wkdir}/bjobcards-dev${RUNTYP}
##echo "#BSUB -L /bin/ksh"          >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -W 03:00"             >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -n 1"                 >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -R "affinity[core]""  >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -R "rusage[mem=5500]"" >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -q dev"                >>${wkdir}/bjobcards-dev${RUNTYP}
  echo "#BSUB -x"                    >>${wkdir}/bjobcards-dev${RUNTYP}

  cd ${wkdir}
  cat ${wkdir}/bjobcards-dev${RUNTYP} ${jobd}/JNAM_SMINIT > ${wkdir}/JNAM_SMINIT.${RUNTYP}
  cp -p ${jobd}/${modeld}.card ${wkdir}
  echo ==========================================================
  echo `date`
  echo  SMINIT JOB SUBMITTED:  $RUNTYP CYCLE $cyc FFHR $ffhr

  bsub <${wkdir}/JNAM_SMINIT.${RUNTYP}

  jobid=`qac -u $USER -d |grep $job | awk '{ print $1 }'`
  sleep 10     

#=================================================================
# Check if job is complete before submitting next forecast hour
#=================================================================
  qchkfl=qname.${RUNTYP}${cyc}
  qname > $qchkfl
  if [ -s $qchkfl ];then
  status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
  while [ "${status}" != "C" ];do
    if [ "${status}" = "RM" ]; then
      err=601
      echo ${err} > FCST_ERR-$job
      exit
    fi
    sleep 60
    qname > $qchkfl
    status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
    if [ $SECONDS -gt 3000 ];then exit;fi
  done
  fi
  echo SMINIT JOB COMPLETED: $err  $RUNTYPE CYCLE $cyc FFHR $ffhr
  echo `date`
  let ffhr=$ffhr+$INCR 
done

rm $qchkfl
#TEST rm $wkdir/JNAM_SMINIT.$RUNTYP
#TEST rm $wkdir/bjobcards-dev$RUNTYP

#echo SUBMIT plotmet.job for $RUNTYP $cyc from fhrs $ffhr to $ENDHRS
export RUNTYP=$RUNTYP
export cyc=$cyc
export strhr=$fhrstr
#bsub < $gemdir/plotmet.job
