#!/bin/ksh
export PATH=${PATH}:.
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

#=======================================================
# Driving script to run a smartinit domain
# Called by DRIVER
# Submits J{MDL}_SMINIT.${RUNTYP}
# RUNTYP : conus ak alaskanest hi pr conusnest2p5 aknest3
#
# Uses ${cfgdir}/smart_para_config --> directory config
# Jeff McQueen       01/29/2013
# Vertical structure 08/27/2013
#=======================================================
###set -x 
typeset -Z2 cyc 

#====================User Sets=======================================
# Location of smart config file to set up directories
cfgdir=${rootd}/parm
export wkdir=${rootd}/working
mkdir -p $wkdir
gemdir=/meso/save/$USER/gempak/sfcplot/smart
export utilscript=${utilscript:-/nwprod/util/ush}

export jobd=${jobd:-`pwd`}

INCR=03            # Forecast hour increment

export MDL=`echo $mdl |tr '[a-z]'  '[A-Z]' `
export NET=$mdl 
if [ $RUNTYP = guam ];then export NET=hiresw;fi

export WALLCLK="1:00"  #TEST

runreg=$RUNTYP
case $RUNTYP in 
    conusnest2p5 ) runreg=conus2p5;;
      alaskanest ) runreg=alaska;;
         aknest3 ) runreg=ak3;;
         dgex_ak ) runreg=ak;;
         dgex_cs ) runreg=conus;;
esac

#================END User Sets=======================================

export ffhr=$fhrstr
export DATA_IN=/stmpp1/${USER}/${modeld}.${model_ver}/${cyc}
mkdir -p $DATA_IN
mkdir -p $DATA_IN/list
while [ $ffhr -le $ENDHRS ];do
  cd ${wkdir}
  if [ $ffhr -lt 10 ];then ffhr="0"${ffhr};fi
  chk3=`expr $ffhr % 3`
  chk6=`expr $ffhr % 6`
  export job="DNG${cyc}.${RUNTYP}-${ffhr}"

# Create and invoke config file needed by Job 
  echo "export RUNTYP=$RUNTYP"   >$wkdir/dng_para_config${RUNTYP}
  echo "export cyc=$cyc"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export RM_TMPDIR=NO"    >>$wkdir/dng_para_config${RUNTYP}
  echo "export mdl=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export NET=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export RUN=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  cat $cfgdir/smart_para_config >>$wkdir/dng_para_config${RUNTYP}
  chmod 755 ${wkdir}/dng_para_config${RUNTYP}

  export PDY=`/nwprod/util/exec/ndate |cut -c 1-8`
  cp -p ${rootd}/docs/${modeld}.ver ${wkdir}
  echo ==========================================================
  echo `date`

# 6 hr interval forecasts use 6 hour old smart files so
# wait until old smart file is created 
  if [ $ffhr -gt $fhrstr -a $chk6 -eq 0 ];then 
    wait=0
    ((HHold=ffhr-6))
    if [ $HHold -lt 10 ];then HHold="0"$HHold;fi
    ffhrsv=$ffhr
    while [ $wait -le 3600 ];do
      smflold=${COM_OUT}/$mdl.$PDY/$mdl.t${cyc}z.smart${runreg}${HHold}.tm00
      if [ ! -s $smflold ];then
        echo  $wait `date +%T` Waiting for $smflold   FFHR=$ffhr
        sleep 60
        ((wait=wait+60))

#       Submit the intermediate hour forecasts while waiting for 6/12 hr files
        if [ $wait -le 60 -a $INCR -le 3 ];then 
          ((fhrnxt=ffhr+INCR))
          while [ $fhrnxt -le $ENDHRS ];do
            if [ $fhrnxt -lt 10 ];then fhrnxt="0"$fhrnxt;fi
            chk6=`expr $fhrnxt % 6`
            if [ $chk6 -ne 0 ];then
              export job="DNG${cyc}.${RUNTYP}-${fhrnxt}"
              echo "export ffhr=$fhrnxt" >> ${wkdir}/dng_para_config${RUNTYP}
              echo "export DATA=/${DATA_IN}/${job}"  >>$wkdir/dng_para_config${RUNTYP}
              . ${wkdir}/dng_para_config${RUNTYP} >dngcfg.out
              sleep 10
              echo `date +%T` $MDL SUBMIT SMINIT JOB :  $RUNTYP CYCLE $cyc FHRNXT $fhrnxt
              ${kickd}/cr8bjob $job $fhrnxt
              bsub < J${MDL}_SMINIT.${RUNTYP}
            fi
            ((fhrnxt=fhrnxt+INCR))
          done
          export INCR=06
          ffhr=$ffhrsv
        fi

      else
        echo $wait $smflold FOUND for FFHR=$ffhr 
        break
      fi
    done 
    if [ $wait -ge 3600 ];then
      echo  `date +%T` $smflold NOT FOUND FOR FFHR=$ffhr
      echo  RUN_ALL for $mdl $RUNTYP $cyc EXITING
      exit
    fi
  fi 

  export job="DNG${cyc}.${RUNTYP}-${ffhr}"
  echo "export ffhr=$ffhr" >> ${wkdir}/dng_para_config${RUNTYP}
  echo "export DATA=/${DATA_IN}/${job}" >>$wkdir/dng_para_config${RUNTYP}
 . ${wkdir}/dng_para_config${RUNTYP} >dngcfg.out
  echo  $wait `date +%T` SUBMIT $MDL SMINIT JOB :  $RUNTYP CYCLE $cyc FFHR $ffhr
  sleep 10     
  ${kickd}/cr8bjob $job $ffhr
  bsub < J${MDL}_SMINIT.${RUNTYP}
  let ffhr=$ffhr+$INCR 
done

rm -f $qchkfl
#TEST rm $wkdir/JNAM_SMINIT.$RUNTYP
#TEST rm $wkdir/dng_para_config${RUNTYP}
rm -f $wkdir/bjobcards-dev$RUNTYP*

#echo SUBMIT plotmet.job for $RUNTYP $cyc from fhrs $ffhr to $ENDHRS
export RUNTYP=$RUNTYP
export cyc=$cyc
export strhr=$fhrstr
#bsub < $gemdir/plotmet.job
