#!/bin/ksh
set -xa
export PATH=${PATH}:.
#export stutil=/hwrf/noscrub/soft/modulefiles
#. /usrx/local/Modules/default/init/ksh
 . /usrx/local/prod/lmod/lmod/init/profile
module load ips/18.0.1.163
module load impi/18.0.1
module load prod_util/1.1.0
module load emc-utils/1.0.0
module load lsf/10.1
echo $cyc
#module load ibmpe lsf ics
#module use $stutil
#module load ruby emc-utils
#module load GrADS/2.0.2
#module load prod_util
#module load /nwpara2/modulefiles/util_shared/v1.0.3 

#=======================================================
# Driving script to run a smartinit domain
# Called by DRIVER
# Submits J{MDL}_SMINIT.${RUNTYP}
# RUNTYP : conus ak alaskanest hi pr conusnest2p5 aknest3
#
# Uses ${cfgdir}/smart_para_config --> directory config
# Jeff McQueen       01/29/2013
# Vertical structure 08/27/2013

#   Jun 2015 Annette Gibbs - Changed smartinit to run on phase 2
# 7 Jul 2015 Annette Gibbs - Changed smartinit output from /stmpp2/$USER to /ptmpp2/$USER and added $PDY to dir
# 7 Jul 2015 Annette Gibbs - $PDY is now determined in DRIVcs2p and DRIV-dgex
#=======================================================
#typeset -Z2 cyc #ffhr fhrnxt ffhrsv HHold strhr
echo $cyc

#====================User Sets=======================================
# Location of smart config file to set up directories
cfgdir=${rootd}/parm
export wkdir=${rootd}/working
mkdir -p $wkdir
#gemdir=/meso/save/$USER/gempak/sfcplot/smart
#plotdir=/meso/save/Annette.Gibbs/plot_smartgrids_para
##export utilscript=${utilscript:-/nwprod/util/ush}

export jobd=${jobd:-`pwd`}

subint=0                  # flag to submit intermediate hour forecasts (see below)

export INCR=${INCR:-03}
export MDL=`echo $mdl |tr '[a-z]'  '[A-Z]' `
export NET=$mdl 
if [ $RUNTYP = guam ];then export NET=hiresw;fi

export WALLCLK="0:45"  #TEST
if [ $RUNTYP = conusnest2p5 ];then export WALLCLK="0:45";fi  #TEST

runreg=$RUNTYP
case $RUNTYP in 
    conusnest2p5 ) runreg=conus2p5;;
      alaskanest ) runreg=alaska;;
         aknest3 ) runreg=ak3;;
         dgex_ak ) runreg=ak;;
         dgex_cs ) runreg=conus;;
         priconest ) runreg=pr;;
         hawaiinest ) runreg=hi;;
esac

#================END User Sets=======================================

export ffhr=$fhrstr
export DATA_IN=/gpfs/dell2/ptmp/${USER}/${modeld}.${nam_smartinit_ver}/${PDY}/${cyc}
mkdir -p $DATA_IN
mkdir -p $DATA_IN/list

while [ $ffhr -le $ENDHRS ];do
  if [ $ffhr -lt 10 ];then ffhr="0"${ffhr};fi
  cd ${wkdir}
  export job="DNG${cyc}.${RUNTYP}-${ffhr}"

# Create and invoke config file needed by Job 
  echo "export RUNTYP=$RUNTYP"   >$wkdir/dng_para_config${RUNTYP}
  echo "export cyc=$cyc"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export RM_TMPDIR=NO"    >>$wkdir/dng_para_config${RUNTYP}
  echo "export mdl=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export NET=$mdl"        >>$wkdir/dng_para_config${RUNTYP}
  echo "export RUN=$mdl"        >>$wkdir/dng_para_config${RUNTYP}

#TEST ****   cat $cfgdir/smart_para_test  >>$wkdir/dng_para_config${RUNTYP}

  cat $cfgdir/smart_para_config  >>$wkdir/dng_para_config${RUNTYP}
  chmod 755 ${wkdir}/dng_para_config${RUNTYP}
 . ${wkdir}/dng_para_config${RUNTYP} >dngcfg.out

# This is now done in DRIVcs2p and DRIV-dgex so I can save 5 days worth of working directory data
# Annette Gibbs

# export PDY=`/nwprod/util/exec/ndate |cut -c 1-8`
#export PDY=20150629 ###TEST

  cp -p ${rootd}/docs/${modeld}.ver ${wkdir}
  echo;echo `date`

# 6 hr interval forecasts use 6 hour old smart files so
# wait until old smart file is created 
  if [ $subint -eq 0 ];then 

#   Submit the intermediate hour forecasts while waiting for 6/12 hr files
    ffhrsv=$ffhr
    fhrnxt=$ffhr
    while [ $fhrnxt -le $ENDHRS ];do
      chk6=`expr $fhrnxt % 6`
      if [ $chk6 -ne 0 -o $fhrnxt -eq $fhrstr ];then
        export job="DNG${cyc}.${RUNTYP}-${fhrnxt}"
        echo "export ffhr=$fhrnxt" >> ${wkdir}/dng_para_config${RUNTYP}
        echo "export DATA=${DATA_IN}/${job}"  >>$wkdir/dng_para_config${RUNTYP}
        . ${wkdir}/dng_para_config${RUNTYP} >dngcfg.out
        sleep 10

        echo `date +%T` $MDL SUBMIT SMINIT JOB :  $RUNTYP CYCLE $cyc FHRNXT $fhrnxt
#      ${kickd}/cr8bjob_poe $job $fhrnxt
       ${kickd}/cr8bjob $job $fhrnxt
module load lsf/10.1
        bsub < J${MDL}_SMINIT.${RUNTYP}
      fi
      ((fhrnxt=fhrnxt+INCR))
      if [ $fhrnxt -lt 10 ];then fhrnxt="0"${fhrnxt};fi
    done
    export INCR=06
    export ffhr=$ffhrsv
    subint=1
  fi 

  wait=0
  while [ $wait -le 3600 -a $ffhr -ge $((fhrstr+06)) ];do
    ((HHold=ffhr-6))
    if [ $HHold -lt 10 ];then HHold="0"${HHold};fi
    smflold=${COMOUT}/$mdl.t${cyc}z.smart${runreg}${HHold}.tm00.grib2

    if [ ! -s $smflold ];then
      echo  $wait `date +%T` Waiting for $smflold   FFHR=$ffhr
      sleep 60
      ((wait=wait+60))
    else
      ((HHold=ffhr-3))
      if [ $HHold -lt 10 ];then HHold="0"${HHold};fi
      smflold=${COMOUT}/$mdl.t${cyc}z.smart${runreg}${HHold}.tm00.grib2
      if [ ! -s $smflold ];then
        echo  $wait `date +%T` Waiting for $smflold   FFHR=$ffhr
        sleep 60
        ((wait=wait+60))
      else
        export job="DNG${cyc}.${RUNTYP}-${ffhr}"
        echo "export ffhr=$ffhr" >> ${wkdir}/dng_para_config${RUNTYP}
        echo "export DATA=${DATA_IN}/${job}" >>$wkdir/dng_para_config${RUNTYP}
        . ${wkdir}/dng_para_config${RUNTYP} >dngcfg.out
        echo  $wait `date +%T` SUBMIT $MDL SMINIT JOB :  $RUNTYP CYCLE $cyc FFHR $ffhr
        sleep 10     
#       ${kickd}/cr8bjob_poe $job $ffhr
        ${kickd}/cr8bjob $job $ffhr
module load lsf/10.1
        bsub -K < J${MDL}_SMINIT.${RUNTYP}
        break
      fi
    fi
  done

  if [ $wait -gt 3600 ];then
    echo "files have not been found, discontinue search"
    exit
  fi

  ((ffhr=ffhr+INCR))
done

#TEST rm $wkdir/JNAM_SMINIT.$RUNTYP
#TEST rm $wkdir/dng_para_config${RUNTYP}
rm -f $wkdir/bjobcards-dev$RUNTYP*

#echo SUBMIT plotmet.job for $RUNTYP $cyc from fhrs $ffhr to $ENDHRS
export RUNTYP=$RUNTYP
export cyc=$cyc
export strhr=$fhrstr
#bsub < $gemdir/plotmet.job

export PDY=$PDY
export cyc=$cyc
date

exit
if [ $runreg = conus2p5 ];then
  pltrun=conusnest
  bsub -K < $plotdir/run_webpage00_${pltrun}_exp_grib2
  bsub -K < $plotdir/run_webpage00_${pltrun}_exp_grib2_hourly
  date
# bsub < ${kickd}/hpss_archive.sh
# $plotdir/make_DNG_page.sh 
#  $plotdir/make_DNG_page_region.sh 
#  bsub < $plotdir/webdiag.bsub
elif [ $runreg = ak3 ];then
  pltrun=ak3
  bsub < $plotdir/run_webpage00_${pltrun}_grib2
  bsub < $plotdir/run_webpage00_${pltrun}_grib2_hourly
elif [ $runreg = ak_rtmages ];then
  pltrun=ak_rtmages
  bsub < $plotdir/run_webpage00_${pltrun}_grib2_hourly
elif [ $runreg = hi ];then
  sleep 1080
  pltrun=hi
  bsub < $plotdir/run_webpage00_${pltrun}_grib2
  bsub < $plotdir/run_webpage00_${pltrun}_grib2_hourly
elif [ $runreg = pr ];then
  sleep 560
  pltrun=pr
  bsub < $plotdir/run_webpage00_${pltrun}_grib2
  bsub < $plotdir/run_webpage00_${pltrun}_grib2_hourly
fi

