#!/bin/ksh
#=======================================================
# Driving script to run all plot metjobs
# calls plotmet.job, plotdiff.job, ftpmet.job
# Jeff McQueen   01/29/2013
# grib dir :  /com/${mdld}/prod/${mdl}.${ymd} (/com/nam/prod/nam.20130715
# mdl file :  ${mdld}.t00z.smart{REGION}{fhr}.tm00 (nam.t12z.smarthi03.tm00)
#=======================================================
export PATH=${PATH}:.
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

typeset -Z2 cyc ffhr

# Plot yesterday to compare to obs
export ymd1=`/nwprod/util/exec/ndate -24 |cut -c 1-8`
export ymd0=`/nwprod/util/exec/ndate |cut -c 1-8`
#export ymd0=20140707
#export ymd1=20140708
export ymd=$ymd1

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 08 ];then export cyc=00;
elif [ $HH -le 14 ];then export cyc=06;
elif [ $HH -le 20 ];then export cyc=12;
else
  export cyc=18
fi

export cyc=12 #TEST

domhrw=;

#==============================================================================
export pltcfg=test     #cfg varbs to plt : smart,nam,nam2,nmm,urma,test

export strhr=00           # Starting forecast hour
export ENDHRS=12          # Ending forecast hour
set -A mdl smart urma     # GRIB model file type (ctl model should be first)
export mdld="nam urma "     # directory header location for dng files

# domains for nam    : conus/conusnest alaskanest  hawaiinest priconest            gfs
# domains for smart  : conus/conus2p5  ak/ak3      hi         pr        ak_rtmages guam
export domains="conus2p5"   #SMART 2.5 km GRID
export REGION2=conusnest    #nest  GRID
#==============================================================================
export scrdir=/meso/save/$USER/gempak/sfcplot/smart
export wkroot=/stmpp1/${USER}/smartplt/$ymd
 mesodir=/ptmpp1/Steven.Levine/gempak4mcqueen 
#TEST mesodir=/meso/noscrub/Jeff.McQueen/gemfiles
mkdir -p $wkroot/list

#copy gempak obs file from tempest
mkdir -p /ptmpp1/${USER}/gemfiles
scp -p wd22jm@tempest.ncep.noaa.gov:/export-4/tempesft/mpyle/obs/sfc/${ymd}.sfc /ptmpp1/Jeff.McQueen/gemfiles >scp.out 2>&1 
cp -rp  $mesodir/${ymd1} /ptmpp1/Jeff.McQueen/gemfiles
cp -rp  $mesodir/${ymd0} /ptmpp1/Jeff.McQueen/gemfiles

for REGION in ${domains}; do
  case ${REGION} in
               conus|conusnest|ak) set -A ptypes met ;;
           conus2p5|ak3) set -A ptypes met ;;
                 hi|pr ) set -A ptypes met ;;
                      *) set -A ptypes met;;
  esac
  export endhrs=$ENDHRS

# SET PLOT AREAS
  for PTYP in ${ptypes[*]};do
    set -A PAREA dset
    case ${REGION} in
      conus|conus2p5|conusnest)
        set -A PAREA dset "bwi**" "oxr***"  "ase****" "boi***" "vgt***";;
                  ak|ak3) set -A PAREA "dset" "pajn****";;
                      hi) set -A PAREA "phnl***";;
                      pr) set -A PAREA "pu";;
       guamnmmb|guamarw)
                set -A PAREA guam
                set -A mdl gfs smart
                export mdld="gfs hiresw";;
    esac

    iparea=0
    npareas=${#PAREA[*]}
    for plotarea in ${PAREA[*]};do  
      export plotarea
      parea=`echo $plotarea |cut -d* -f1`
      ((iparea=iparea+1))

#=========================================================
#     Set grid Regions for control vs smart init comparisons
#=========================================================
      export reg="$REGION $REGION2"

#=========================================================
#     Submit plotmet or plotdiff jobs
#=========================================================
      export endhrs=$ENDHRS
      export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
      jobpar=;
      if [ ${mdl[0]} != smart ];then jobmdl=${mdl[0]}
      elif [ ${mdl[1]} != smart ];then jobmdl=${mdl[1]}
      else; jobmdl=`echo $mdld | cut -d" " -f1`;fi
      if [ ${parea} != dset -a $parea != ${REGION} ];then jobpar=${REGION}${parea};fi
      export job="${jobmdl}${cyc}.${REGION}${jobpar}-${PTYP}"

      if [ ${parea} = dset ];then jobpar=${REGION};fi
      export wkdir=${wkroot}/${jobmdl}${jobpar}${cyc}
      export wkdir2=${wkroot}/d2${jobmdl}${jobpar}${cyc}
      export gemfile=${mdl}${REGION}.gem${ENDHRS}
      echo;echo $iparea `date +%T`  SUBMIT $job GAREA $plotarea \
        CYCLE: $cyc Z FHRS $strhr to $ENDHRS

      echo "#!/bin/ksh --login" >hdr
      echo "#BSUB -J ${job}"  >>hdr
      echo "#BSUB -oo ${wkroot}/list/${job} " >>hdr
      echo "#BSUB -eo ${wkroot}/list/${job} " >>hdr
      if [ $PTYP = diff ];then 
        cat hdr ${scrdir}/plot${PTYP} > plot${PTYP}_${REGION}${parea}.job
      else
        cat hdr ${scrdir}/plotnam > plot${PTYP}_${REGION}${parea}.job
     fi

      chmod 755 plot${PTYP}_${REGION}${parea}.job
     bsub < plot${PTYP}_${REGION}${parea}.job
#TEST      plot${PTYP}_${REGION}${parea}.job >$job.out 2>&1 &

      sleep 10;rm -f plot${PTYP}_${REGION}${parea}.job hdr

exit

#=================================================================
# Check if 1st job gemfiles are created to continue with sub-areas or
# last sub-area job is complete before FTPing the plots for current region
#=================================================================
     if [ $npareas -gt 1 -a $iparea -eq 1 -a $PTYP = met ];then
       echo;echo $iparea `date +%T` WAIT for JOB $job to COMPLETE  Secs $SECONDS
       export SECONDS=0
       jobid=`qac -u $USER -d |grep $job | awk '{ print $1 }'`
       sleep 10
       qchkfl=${wkdir}/qname.${PTYP}_${REGION}${parea}
       qname > $qchkfl

       if [ -s $qchkfl ];then
         status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
         while [ "${status}" != "C" ];do
           if [ "${status}" = "RM" ]; then
             err=601
             echo ${err} > PLOT_ERR-$job
             exit
           fi
           sleep 60

           qname > $qchkfl
           status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
           if [ $SECONDS -gt 7200 ];then exit;fi  

#          GEMFILE needed for sub-areas plotting found
           if [ -s ${wkdir}/${gemfile} ];then 
             echo GEMFILE $wkdir $gemfile FOUND
             sleep 60
             break
           fi
           echo `date +%T` WAITING for JOB $jobid to complete
         done
       fi
     fi
    done  #PLOT AREA 

#===============================================================
#   FTP plots
#===============================================================
    rm -f $qchkfl
    for plotarea in ${PAREA[*]};do  
      sleep 30
      parea=`echo $plotarea |cut -d* -f1`
      export PTYP
      if [ $parea != dset -a $parea != $REGION ];then
        export ftparea=${REGION}$parea
      else
        export ftparea=$REGION 
      fi
      export ftpmdl="${mdld[*]}"
      echo SUBMIT FTP_MET $ftpmdl $ftparea $PTYP
      $scrdir/FTP_MET 
    done

  done    #PLOT TYPES
done      #REGIONS

echo;echo `date +%T` RUN_GEM COMPLETED CYCLE $cyc   PLTCFG  $pltcfg
