#!/bin/ksh
#=======================================================
# Driving script to run all plot metjobs
# calls plotmet.job, plotdiff.job, ftpmet.job
# Jeff McQueen   01/29/2013
# grib dir :  /com/${mdld}/prod/${mdl}.${ymd} (/com/nam/prod/nam.20130715
# mdl file :  ${mdld}.t00z.smart{REGION}{fhr}.tm00 (nam.t12z.smarthi03.tm00)
#=======================================================
export PATH=${PATH}:.
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

typeset -Z2 cyc ffhr

# Plot yesterday to compare to obs
export ymd=`/nwprod/util/exec/ndate -24 |cut -c 1-8`

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 08 ];then export cyc=00;
elif [ $HH -le 14 ];then export cyc=06;
elif [ $HH -le 20 ];then export cyc=12;
else
  export cyc=18
fi

domhrw=;
domdgx="dgex_conus"
set -A pareadgex "dset" "sdb***" "ase****" "boi***" "vgt***"
case $cyc in 00|12) 
  domdgx="dgex_ak"
  set -A pareadgex "dset" "pajn****"
  domhrw="guamnmmb guamarw";;
esac

#============================================================================
export pltcfg=smdgex  #cfg varbs to plt : smart,nam,nam2,nmm,test

export INCR=06            # Forecast hour increment

# domains for nam    : conus/conusnest alaskanest  hawaiinest priconest            gfs
# domains for smart  : conus/conus2p5  ak/ak3      hi         pr        ak_rtmages guam
# export domains="hi pr conus ak ak3 conus2p5"
# domains for dgex   : dgex_conus         dgex_ak3
export domains="${domdgx}"
#==============================================================================
export scrdir=/meso/save/$USER/gempak/sfcplot/smart
export wkroot=/stmpp1/${USER}/smartplt
mkdir -p $wkroot/list

#copy gempak obs file from tempest
echo SCP SFC file $ymd
mkdir -p /ptmpp1/${USER}/gemfiles
scp -p wd22jm@tempest.ncep.noaa.gov:/export-4/tempest/mpyle/obs/sfc/${ymd}.sfc /ptmpp1/Jeff.McQueen/gemfiles >scp.out 2>&1 

for REGION in ${domains}; do
  case ${REGION} in
               conus|ak) export strhr=00;export ENDHRS=00;set -A ptypes met diff;;
           conus2p5|ak3) export strhr=03;export ENDHRS=12;set -A ptypes met diff;;
                 hi|pr ) export strhr=00;export ENDHRS=12;set -A ptypes met diff;;
                      *) set -A ptypes met;;
  esac
  export endhrs=$ENDHRS

# SET PLOT AREAS
  for PTYP in ${ptypes[*]};do
    set -A PAREA dset
    case ${REGION} in
      conus|conus2p5|conusnest)
        set -A PAREA "dset" "sdb***" "ase****" "boi***" "vgt***";;
#       set -A PAREA "dset" "sfo*" "nyc**" "mfr**" "sdb***" "ase****" "boi***" "vgt***";;
                  ak|ak3) set -A PAREA "dset" "pajn****";;
                      hi) set -A PAREA "phnl***";;
                      pr) set -A PAREA "pu";;
       guamnmmb|guamarw)
                set -A PAREA guam
                set -A mdl gfs smart
                export mdld="gfs hiresw";;
  dgex_ak3|dgex_conus|dgex) set -A PAREA ${pareadgex[*]}
                        set -A mdl dgex smart
                        export mdld="dgex dgex"
                        export strhr=84
                        export ENDHRS=132;;     #TEST

    esac

    iparea=0
    npareas=${#PAREA[*]}
    for plotarea in ${PAREA[*]};do  
      export plotarea
      parea=`echo $plotarea |cut -d* -f1`
      ((iparea=iparea+1))

#=========================================================
#     Set grid Regions for control vs smart init comparisons
#=========================================================
      export reg="$REGION $REGION"
      if [ ${mdl[0]} != ${mdl[1]} ];then
        if [ ${mdl[1]} = nam ];then
#TEST         export mdld="nam nam"  # grib file directories (nam,hiresw,gfs,dgex)
         case $REGION in
           conus|conus2p5) export reg="${REGION} conusnest";;
           ak|ak3|aknest3) export reg="${REGION} alaskanest";;
         guamnmmb|guamarw) export reg="${REGION} guam";;
                       hi) export reg="${REGION} hawaiinest";export ENDHRS=60;;
                       pr) export reg="${REGION} priconest";;
     dgex|dgex_ak|dgex_conus)
                             export REGION=`echo $REGION |cut -d_ -f2`
                             export reg="${REGION} conus"
                             if [ $REGION = ak ];then
                               export reg="${REGION} alaska"
                             fi;;

         esac
        elif [ ${mdl[1]} = smart ];then
#TEST         export mdld="${mdl[0]} nam"
         case $REGION in
           conus|conus2p5) export reg="conusnest ${REGION}";;
           ak|ak3|aknest3) export reg="alaskanest ${REGION}";;
         guamnmmb|guamarw) export reg="guam ${REGION}";;
                       hi) export reg="hawaiinest $REGION"; export ENDHRS=60;;
                       pr) export reg="priconest ${REGION}";;
     dgex|dgex_ak|dgex_conus)
                             export REGION=`echo $REGION |cut -d_ -f2`
                             export reg="conus ${REGION}"
                             if [ $REGION = ak ];then
                               export reg="alaska ${REGION}"
                             fi;;

         esac
        else
          echo " model prefix to plot  ${mdl[*]} "
        fi
      fi

#=========================================================
#     Submit plotmet or plotdiff jobs
#=========================================================
      export endhrs=$ENDHRS
      export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
      jobpar=;
      jobmdl=`echo $mdld | cut -d" " -f1`
      export gemfile=${jobmdl}${REGION}.gem${ENDHRS}
      if [ ${mdl[0]} = smart ];then
        export gemfile=${mdl[0]}${REGION}.gem${ENDHRS}
        jobmdl=${mdl[1]}
      else
        if [ ${mdl[1]} = smart ];then  
          export gemfile=${mdl[1]}${REGION}.gem${ENDHRS}
          jobmdl=${mdl[0]}
        fi
      fi
      if [ ${parea} != dset -a $parea != ${REGION} ];then jobpar=${REGION}${parea};fi
      export job="${jobmdl}${cyc}.${REGION}${jobpar}-${PTYP}"

      if [ ${parea} = dset ];then jobpar=${REGION};fi
      export wkdir=${wkroot}/${jobmdl}${jobpar}${cyc}
      export wkdir2=${wkroot}/d2${jobmdl}${jobpar}${cyc}
      echo;echo $iparea `date +%T`  SUBMIT $job GAREA $plotarea \
        CYCLE: $cyc Z FHRS $strhr to $ENDHRS

      echo "#!/bin/ksh --login" >hdr
      echo "#BSUB -J ${job}"  >>hdr
      echo "#BSUB -oo ${wkroot}/list/${job} " >>hdr
      echo "#BSUB -eo ${wkroot}/list/${job} " >>hdr
      cat hdr ${scrdir}/plot${PTYP} > plot${PTYP}_${REGION}${parea}.job

      bsub < plot${PTYP}_${REGION}${parea}.job
      sleep 10;rm -f plot${PTYP}_${REGION}${parea}.job hdr

#=================================================================
# Check if 1st job gemfiles are created to continue with sub-areas or
# last sub-area job is complete before FTPing the plots for current region
#=================================================================
     if [ $iparea -eq 1 -a $PTYP = met ];then
       echo;echo $iparea `date +%T` WAIT for JOB $job to COMPLETE  Secs $SECONDS
       echo $wkdir
       echo $wkdir2
       echo $gemfile
       export SECONDS=0
       jobid=`qac -u $USER -d |grep $job | awk '{ print $1 }'`
       sleep 10
       qchkfl=qname.${PTYP}_${REGION}${parea}
       qname > $qchkfl

       if [ -s $qchkfl ];then
         status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
         while [ "${status}" != "C" ];do
           if [ "${status}" = "RM" ]; then
             err=601
             echo ${err} > PLOT_ERR-$job
             exit
           fi
           sleep 60

           qname > $qchkfl
           status=`grep $jobid $qchkfl  | awk '{ print $2 }'`
           if [ $SECONDS -gt 7200 ];then break;fi  

#          GEMFILE needed for sub-areas plotting found
#          dgex plots are vs smart so one directory may not have smart...gif
           if [ -s ${wkdir}/${gemfile} -o -s {wkdir2}/${gemfile} ];then 
             echo GEMFILE $wkdir $gemfile FOUND
             sleep 60
             break
           fi
           echo `date +%T` WAITING for JOB $jobid to complete
         done
       fi
     fi
    done  #PLOT AREA 

#===============================================================
#   FTP plots
#===============================================================
    rm -f $qchkfl
    for plotarea in ${PAREA[*]};do  
      sleep 30
      parea=`echo $plotarea |cut -d* -f1`
      export PTYP
      if [ $parea != dset -a $parea != $REGION ];then
        export ftparea=${REGION}$parea
      else
        export ftparea=$REGION 
      fi
      export ftpmdl="${mdld[*]}"
      echo SUBMIT FTP_MET $ftpmdl $ftparea $PTYP
      $scrdir/FTP_MET 
    done

  done    #PLOT TYPES
done      #REGIONS

echo;echo `date +%T` RUN_GEM COMPLETED CYCLE $cyc   PLTCFG  $pltcfg
