#!/bin/ksh
#=======================================================
# Driving script to run all plot metjobs
# calls plotmet.job, plotdiff.job, ftpmet.job
# Jeff McQueen   01/29/2013
# grib dir :  /com/${mdld}/prod/${mdl}.${ymd} (/com/nam/prod/nam.20130715
# mdl file :  ${mdld}.t00z.smart{REGION}{fhr}.tm00 (nam.t12z.smarthi03.tm00)
#=======================================================
export PATH=${PATH}:.
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

typeset -Z2 cyc ffhr

# Plot yesterday to compare to obs
export ymd1=`/nwprod/util/exec/ndate -24 |cut -c 1-8`
export ymd0=`/nwprod/util/exec/ndate |cut -c 1-8`
export ymd=$ymd1  #today

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 08 ];then export cyc=00;
elif [ $HH -le 14 ];then export cyc=06;
elif [ $HH -le 20 ];then export cyc=12;
else
  export cyc=18
fi
#TEST  export cyc=00   #TEST

#==============================================================================
export pltcfg=test    #cfg varbs to plt : smart,nam,nam2,nmm,test

export strhr=00           # Starting forecast hour
export ENDHRS=24          # Ending forecast hour
export INCR=03            # Forecast hour increment
set -A mdl smart nam    # GRIB model file type (ctl model should be first)
export mdld="nam nam"     # directory header location for dng files

export domains="conus2p5 hi pr ak3"
set -A REGION2 conusnest hawaiinest priconest alaskanest

# domains for nam    : conus/conusnest alaskanest  hawaiinest priconest            gfs
# domains for smart  : conus/conus2p5  ak/ak3      hi         pr        ak_rtmages guam
domhrw=;
#==============================================================================
export scrdir=/meso/save/$USER/gempak/sfcplot/smart
export wkroot=/stmpp1/${USER}/namplt/$ymd
mkdir -p $wkroot/list

#copy gempak obs file from tempest
mkdir -p /ptmpp1/${USER}/gemfiles
scp -p wd22jm@tempest.ncep.noaa.gov:/export-4/tempest/mpyle/obs/sfc/${ymd1}.sfc /ptmpp1/Jeff.McQueen/gemfiles >scp.out 2>&1 
scp -p wd22jm@tempest.ncep.noaa.gov:/export-4/tempest/mpyle/obs/sfc/${ymd0}.sfc /ptmpp1/Jeff.McQueen/gemfiles >scp.out 2>&1 
cp -rp  /ptmpp1/Steven.Levine/gempak4mcqueen/${ymd1} /ptmpp1/Jeff.McQueen/gemfiles
cp -rp  /ptmpp1/Steven.Levine/gempak4mcqueen/${ymd0} /ptmpp1/Jeff.McQueen/gemfiles

ireg=0
ENDHSUB=$ENDHRS
for REGION in ${domains[*]}; do
  case ${REGION} in
               conus|ak) export strhr=00;export ENDHRS=24;set -A ptypes met ;;
           conus2p5|ak3) set -A ptypes met ;;
                 hi|pr ) export strhr=00;export ENDHRS=24;set -A ptypes met ;;
                      *) set -A ptypes met;;
  esac
  ENDHDST=12

# Set grid Regions for control vs model2 REGION2 comparisons
  export reg="$REGION ${REGION2[ireg]}"

#=========================================================
# First create gempak files for each domain and region (nagrib)
#=========================================================
  export plotarea=dset
  export endhrs=$ENDHRS
  export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
  echo;echo $iparea `date +%T`  SUBMIT nagrib job $ymd  CYCLE: $cyc Z FHRS $strhr to $ENDHRS
  job=nagrib$mdl$cyc
  echo "#!/bin/ksh --login" >nhdr
  echo "#BSUB -J $job"  >>nhdr
  echo "#BSUB -oo ${wkroot}/list/${job} " >>nhdr
  echo "#BSUB -eo ${wkroot}/list/${job} " >>nhdr
  cat nhdr ${scrdir}/plotnagrib > $job.job
  bsub -K < $job.job

# BEGIN PLOT JOB
  for PTYP in ${ptypes[*]};do
    set -A PAREA dset
#   SET PLOT AREAS 
    case ${REGION} in
      conus2p5|conusnest)
      set -A PAREA "dset" "bwi**" "oxr**" "hjo**" "ase****" "boi***" "vgt***" "swse";;
                    ak3|alaskanest) set -A PAREA "dset" "pajn****";;
                     hi|hawaiinest) set -A PAREA "phny*";;
                     pr|priconest) set -A PAREA "pu";;
    esac

    iparea=0
    npareas=${#PAREA[*]}
    for plotarea in ${PAREA[*]};do  
      export plotarea
      parea=`echo $plotarea |cut -d* -f1`
      ((iparea=iparea+1))
      if [ $npareas -eq 1 ];then iparea=0;fi

#=========================================================
#     Submit plotmet or plotdiff jobs
#=========================================================
      export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
      jobpar=;
      if [ ${mdl[0]} != smart ];then jobmdl=${mdl[0]}
      elif [ ${mdl[1]} != smart ];then jobmdl=${mdl[1]}
      else; jobmdl=`echo $mdld | cut -d" " -f1`;fi
      if [ ${parea} != dset -a $parea != ${REGION} ];then jobpar=${REGION}${parea};fi
      export job="${jobmdl}${cyc}.${REGION}${jobpar}-${PTYP}"
      export endhrs=$ENDHSUB
      if [ ${parea} = dset ];then 
         jobpar=${REGION}
         export endhrs=$ENDHDST
      fi
      export wkdir=${wkroot}/${jobmdl}${jobpar}${cyc}
      export wkdir2=d2${wkroot}/${jobmdl}${jobpar}${cyc}

      echo "#!/bin/ksh --login" >nhdr
      echo "#BSUB -J ${job}"  >>nhdr
      echo "#BSUB -oo ${wkroot}/list/${job} " >>nhdr
      echo "#BSUB -eo ${wkroot}/list/${job} " >>nhdr
      cat nhdr ${scrdir}/plotnam > plot${PTYP}_${REGION}${parea}.job

      echo;echo $iparea `date +%T`  SUBMIT $job GAREA $plotarea \
      CYCLE: $cyc Z FHRS $strhr to $ENDHRS
#=================================================================
      bsub  < plot${PTYP}_${REGION}${parea}.job
#=================================================================
      sleep 10;rm -f plot${PTYP}_${REGION}${parea}.job nhdr
    done  #PLOT AREA 

#===============================================================
#   FTP plots
#===============================================================
    for plotarea in ${PAREA[*]};do  
      export PTYP    
      parea=`echo $plotarea |cut -d* -f1`
      export ftparea=$REGION
      if [ $parea != dset -a $parea != $REGION ];then
        export ftparea=${REGION}$parea
      fi
      export ftpmdl="${mdld[*]}"
      echo SUBMIT FTP_MET $ftpmdl $ftparea $PTYP
      $scrdir/FTP_MET 
    done

  done    #PLOT TYPES
  ((ireg=ireg+1))
done      #REGIONS

rm -f nagrib*$cyc.job
echo;echo `date +%T` RUN_GEM COMPLETED CYCLE $cyc   PLTCFG  $pltcfg
