#!/bin/ksh
#=======================================================
# Driving script to run all plot metjobs
# calls plotmet.job, plotdiff.job, ftpmet.job
# Jeff McQueen   01/29/2013
# grib dir :  /com/${mdld}/prod/${mdl}.${ymd} (/com/nam/prod/nam.20130715
# mdl file :  ${mdld}.t00z.smart{REGION}{fhr}.tm00 (nam.t12z.smarthi03.tm00)
#=======================================================
export PATH=${PATH}:.
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

typeset -Z2 cyc ffhr

# Plot yesterday to compare to obs
export ymd1=`/nwprod/util/exec/ndate -24 |cut -c 1-8`
export ymd0=`/nwprod/util/exec/ndate |cut -c 1-8`
export ymd=$ymd1

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 08 ];then export cyc=00;
elif [ $HH -le 14 ];then export cyc=06;
elif [ $HH -le 20 ];then export cyc=12;
else
  export cyc=18
fi

#==============================================================================
export pltcfg=smart   #cfg varbs to plt : smart,nam,nam2,nmm,test

export strhr=00           # Starting forecast hour
export ENDHRS=24          # Ending forecast hour
export INCR=03            # Forecast hour increment
set -A mdl smart smart    # GRIB model file type (ctl model should be first)
export mdld="nam nam"     # directory header location for dng files

# domains for nam    : conus/conusnest alaskanest  hawaiinest priconest            gfs
# domains for smart  : conus/conus2p5  ak/ak3      hi         pr        ak_rtmages guam
domhrw=;
case $cyc in 00|12)
  domhrw="guamnmmb guamarw";;
esac
export domains="hi pr ak conus ak3 conus2p5 "
#==============================================================================
export scrdir=/meso/save/$USER/gempak/sfcplot/smart
export wkroot=/stmpp1/${USER}/smartplt
mkdir -p $wkroot/list

#copy gempak obs file from tempest
mkdir -p /ptmpp1/${USER}/gemfiles
scp -p wd22jm@tempest.ncep.noaa.gov:/export-4/tempest/mpyle/obs/sfc/${ymd}.sfc /ptmpp1/Jeff.McQueen/gemfiles >scp.out 2>&1 
cp -rp  /ptmpp1/Steven.Levine/gempak4mcqueen/${ymd1} /ptmpp1/Jeff.McQueen/gemfiles
cp -rp  /ptmpp1/Steven.Levine/gempak4mcqueen/${ymd0} /ptmpp1/Jeff.McQueen/gemfiles


for REGION in ${domains}; do
  case ${REGION} in
               conus|ak) export strhr=00;export ENDHRS=24;set -A ptypes met diff;;
           conus2p5|ak3) export strhr=00;export ENDHRS=24;set -A ptypes met diff;;
                 hi|pr ) export strhr=00;export ENDHRS=24;set -A ptypes met diff;;
                      *) set -A ptypes met;;
  esac


#=========================================================
#     Set grid Regions for control vs smart init comparisons
#=========================================================
  export reg="$REGION $REGION"
  if [ ${mdl[0]} != ${mdl[1]} ];then
    if [ ${mdl[1]} = nam ];then
      export mdld="nam nam"  # grib file directories (nam,hiresw,gfs,dgex)
      case $REGION in
           conus2p5) export reg="${REGION} conusnest";;
        ak3|aknest3) export reg="${REGION} alaskanest";;
   guamnmmb|guamarw) export reg="${REGION} guam";;
                 hi) export reg="${REGION} hawaiinest";;
                 pr) export reg="${REGION} priconest";;
      esac
    elif [ ${mdl[1]} = smart ];then
      export mdld="${mdl[0]} nam"
      case $REGION in
        conus|conus2p5) export reg="conusnest ${REGION}";;
        ak|ak3|aknest3) export reg="alaskanest ${REGION}";;
      guamnmmb|guamarw) export reg="guam ${REGION}";;
                    hi) export reg="hawaiinest $REGION";;
                    pr) export reg="priconest ${REGION}";;
      esac
    else
      echo " model prefix to plot  ${mdl[*]} "
    fi
  fi

# Create gempak files for each domain
  export plotarea=dset
  export endhrs=$ENDHRS
  ENDHSUB=$ENDHRS
  ENDHDST=12
  export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
  echo;echo $iparea `date +%T`  SUBMIT nagrib job $ymd CYCLE: $cyc Z FHRS $strhr to $ENDHRS
  job=nagrib$mdl$REGION$cyc
  echo "#!/bin/ksh --login" >hdr
  echo "#BSUB -J $job"  >>hdr
  echo "#BSUB -oo ${wkroot}/list/${job} " >>hdr
  echo "#BSUB -eo ${wkroot}/list/${job} " >>hdr
  cat hdr ${scrdir}/plotnagrib > $job.job
  bsub -K < $job.job

# BEGIN PLOT JOB
#  SET PLOT AREAS 
  for PTYP in ${ptypes[*]};do
    set -A PAREA dset
    case ${REGION} in
      conus2p5|conusnest)
        set -A PAREA "dset" "bwi**" "oxr**" "hjo**" "ase****" "boi***" "vgt***" "swse";;
#        set -A PAREA "dset" "mmho" "hjo**" "oxr***" "ase****" "boi***" "vgt***";;
#       set -A PAREA "dset" "sfo*" "nyc**" "mfr**" "sdb***" "ase****" "boi***" "vgt***";;
                    ak3) set -A PAREA "dset" "pajn****";;
                      hi) set -A PAREA "phny*";;
                      pr) set -A PAREA "pu";;
       guamnmmb|guamarw)
                set -A PAREA guam
                set -A mdl gfs smart
                export mdld="gfs hiresw";;
    esac

    iparea=0
    npareas=${#PAREA[*]}
    for plotarea in ${PAREA[*]};do  
      export endhrs=$ENDHSUB
      export plotarea
      parea=`echo $plotarea |cut -d* -f1`
      ((iparea=iparea+1))
      if [ $npareas -eq 1 ];then iparea=0;fi
      if [ ${parea} = dset ];then
        jobpar=${REGION}
        export endhrs=$ENDHDST
      fi

#=========================================================
#     Submit plotmet or plotdiff jobs
#=========================================================
      export mdlin="${mdl[*]}"    #mdlin is passed to jobs and scripts
      jobpar=;
      if [ ${mdl[0]} != smart ];then jobmdl=${mdl[0]}
      elif [ ${mdl[1]} != smart ];then jobmdl=${mdl[1]}
      else; jobmdl=`echo $mdld | cut -d" " -f1`;fi
      if [ ${parea} != dset -a $parea != ${REGION} ];then jobpar=${REGION}${parea};fi
      export job="${jobmdl}${cyc}.${REGION}${jobpar}-${PTYP}"
      if [ ${parea} = dset ];then jobpar=${REGION};fi
      export wkdir=${wkroot}/${jobmdl}${jobpar}${cyc}
      export wkdir2=d2${wkroot}/${jobmdl}${jobpar}${cyc}

      echo "#!/bin/ksh --login" >hdr
      echo "#BSUB -J ${job}"  >>hdr
      echo "#BSUB -oo ${wkroot}/list/${job} " >>hdr
      echo "#BSUB -eo ${wkroot}/list/${job} " >>hdr
      cat hdr ${scrdir}/plot${PTYP} > plot${PTYP}_${REGION}${parea}.job

      echo;echo $iparea `date +%T`  SUBMIT $job GAREA $plotarea \
      CYCLE: $cyc Z FHRS $strhr to $ENDHRS
#=================================================================
      bsub  < plot${PTYP}_${REGION}${parea}.job
#=================================================================
      sleep 10;rm -f plot${PTYP}_${REGION}${parea}.job hdr
    done  #PLOT AREA 

#===============================================================
#   FTP plots
#===============================================================
    for plotarea in ${PAREA[*]};do  
      sleep 30
      parea=`echo $plotarea |cut -d* -f1`
      export PTYP
      if [ $parea != dset -a $parea != $REGION ];then
        export ftparea=${REGION}$parea
      else
        export ftparea=$REGION 
      fi
      export ftpmdl="${mdld[*]}"
      echo SUBMIT FTP_MET $ftpmdl $ftparea $PTYP
      $scrdir/FTP_MET 
    done

  done    #PLOT TYPES
done      #REGIONS

rm -f nagrib*$cyc.job
echo;echo `date +%T` RUN_GEM COMPLETED CYCLE $cyc   PLTCFG  $pltcfg
