#!/bin/ksh
# Create ecf trigger jobs for smartinit
# Jeff McQueen 3/20/14
wdir=`pwd`
cd $wdir
fhr=78
endhr=192
mdl=dgex
reg=cs
file=${wdir}/j${mdl}_sminit_${reg}_fHH.ecf
if [ -s $file ];then
while [ $fhr -le $endhr ]; do
  sed s/HH/$fhr/g $file > j${mdl}_sminit_${reg}_f${fhr}.ecf
#####TEST  svn add j${mdl}_sminit_${reg}_f${fhr}.ecf
  ((fhr=fhr+3))
done
else
  echo $wdir
  echo $file  NOT FOUND
fi
