#!/bin/ksh
# nam_smartinit configuration
# Jeff McQueen 01/2013 

. /usrx/local/Modules/default/init/ksh
module load prod_util

# OUTPUT REGION TO DOWNSCALE TO
# valid RUNTYP=conus,ak,hi,pr,conusnest2p5,aknest3,dgex_ak,dgex_cs,guamnmmb,guamarw
#TEST typeset -Z2 ffhr
export RUN_ENVIR=dev
export envir=dev

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# SENDECF: If the job is to be running using SMS, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#
#  USED BY RUN_ALL JOB to set up Development input and output file directies
#####################################################################################
export SENDECF=NO
export SENDDBN=NO
export SENDDBN_GB2=NO
export DBNROOT=/nwprod/spa_util/para_dbn
export KEEPDATA=${KEEPDATA:-%KEEPDATA:YES%}
export nam_ver=v3.1.6
export dgex_ver=v3.1.1

export HOMEdng=/meso/save/$USER/smartinit.${nam_smartinit_ver}             # dng software root dir
echo HOMEdng $HOMEdng
export utilparm=$HOMEdng/util/parm  # grib2 parm files dir
export EXECnam=/nwprod/nam.$nam_ver/exec    # Location of nam_prdgen
export EXECdgex=/nwprod/dgex.$dgex_ver/exec   # Location of dgex_prdgen
#export EXEChiresw=/meso/save/Matthew.Pyle/hiresw_vert/exec

#TEST WITH Dana's GFS changes
#export EXECdng=/global/save/$USER/svn/smartinit/trunk/exec

export COMROOTp1=${COMROOTp1:-/com}
export GESROOTp1=${GESROOTp1:-/nwges}
export NWROOTp1=/nwprod
export NWROOT=/nw${envir}2
export PCOMROOT=${PCOMROOT:-/pcom2/${envir}}

export COMROOT=/com2
export gespath=/nwges2/prod          
## Test with Eric's NAMRR PARA
export GESIN=/nwges2/prod          
#export GESIN=/ptmpd3/Eric.Rogers/nwges/para
#export GESIN=/com2/nam/para
#export GESIN=/meso2/noscrub/Eric.Rogers/nwges/para
export COM_IN=${COMROOT}/${mdl}/prod 

#TEST WITH Eric's NAM PARA     
#TEST export COMROOT="/meso/noscrub/Eric.Rogers/com"
#TEST export gespath=/meso/noscrub/Eric.Rogers/nwges/para
#TEST export COM_IN=${COMROOT}/${mdl}/paranco    #TEST**********************

## Test with Eric's NAM PARA
export COM_IN=/meso2/noscrub/Eric.Rogers/com/${mdl}/para 
export COM_IN=/com2/${mdl}/prod 
#export COM_IN=/ptmpd3/Eric.Rogers/com/${mdl}/para 
#export COM_IN=/meso2/noscrub/Annette.Gibbs/com/${mdl}/para
#export COM_IN=/meso2/noscrub/Jacob.Carley/com/${mdl}/rt
#export COM_IN=/meso2/noscrub/Annette.Gibbs/com/${mdl}/rt
if [ $mdl = dgex ]; then
export COM_IN=/meso2/noscrub/Eric.Rogers/com/${mdl}/para
#export COM_IN=/meso2/noscrub/Annette.Gibbs/com/${mdl}/para
fi
## End Test

# for dgex downscling thru 192 forecast hours, can use locally created gefs files
#export COM_SREF=${COMROOT}/sref/prod   
# new location of SREF
export COM_SREF=/com2/sref/prod
#export COM_SREF=/meso2/noscrub/Annette.Gibbs/com2/sref/prod


export DATA_IN=/ptmpp2/$USER/smartinit.${nam_smartinit_ver}/$PDY/$cyc
export DATAROOT=/ptmpp2/$USER/smartinit.${nam_smartinit_ver}/$PDY/$cyc

export COM_OUT=/meso2/noscrub/$USER/${nam_smartinit_ver}
#TEST export COM_OUT=/ptmpp2/$USER
export pcom=${pcom:-${COM_OUT}/pcom/nam}
export PCOM=${PCOM:-${COM_OUT}/pcom/nam}
export jlogfile=${COM_OUT}/jlogfile.`date +%Y%m%d`
