RUNTYP       rg   outreg   mdlgrd   SREF-GRD	GRDTYP 	 ogrd   gtyp nx  ny   lat1  lon1 gdt tlon   dx  dy
------------------------------------------------------------------------------------------------------------------
hawaiinest   hi   hi       hawaiinest 243      natlev   196     196
priconest    pr   pr       priconest  212      natlev   195     195 
aknest3      ak3  ak3      alaskanest 216      natlev    91     5  1649 1105 40530 181429 8 210000 2976 2976
conusnest2p5 con  conus2p5 conusnest  212      natlev   188     3  2345 1597 19229 233723 8 265000 2540 2540

