#!/bin/ksh
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use /hwrf/noscrub/soft/modulefiles
module load ruby emc-utils

#===================================================================
# Submit several nam_smartinit domain runs
# Calls:  RUN_ALL which submits each RUNTYP domain JNAM_SMINIT job
# Jeff McQueen   02/2013
#====================================================================

# set job directory needed if running from cron
export jobd=/meso/save/$USER/smart-dev/jobs
cd $jobd

#Set the correct ush to use
ln -fs /meso/save/$USER/smart-dev/ush/nam_smartinit.test /meso/save/$USER/smart-dev/ush/nam_smartinit.sh

# Determine cycle  (normally set in job)
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 06 ];then export cyc=00;
elif [ $HH -le 12 ];then export cyc=06;
elif [ $HH -le 18 ];then export cyc=12;
else 
  export cyc=18
fi 
export cyc=06  #TEST

export fhrstr=00  #Normally set in job
export ENDHRS=12

#07/13: change to run ak and alaskanest separately for good output listing
### for RUNTYP in conus ak alaskanest pr conusnest2p5 aknest3 guam;do

for RUNTYP in conus;do
  export mdl=nam          #NCO ENVIR VAR ${RUN}
  if [ $RUNTYP = guam ];then export mdl=hiresw;fi
  export NET=$mdl         #NCO ENVIR VARIABLES
  export RUN=$mdl         #NCO ENVIR VARIABLES
  export RUNTYP=$RUNTYP   #Normally set in job

# Remove older directories
  dayrm=$( echo `/nwprod/util/exec/ndate -120` |cut -c 1-8 )
  Y=$(echo $PDY | cut  -c 1-4 )
  M=$(echo $PDY | cut  -c 5-6 )
  D=$(echo $PDY | cut  -c 7-8 )
  wdayd=$Y$M$D
  rm -rf /ptmp/${USER}/${RUNTYP}/$mdl.${wdayd}

# Create and submit JNAM_SMINIT job

  echo SUBMIT RUN_ALL $RUNTYP  CYC $cyc
  $jobd/RUN_ALL >/stmp/$USER/smart-dev/list/smout-${RUNTYP}${cyc} 2>&1 &
  sleep 10
done
