#!/bin/ksh
export stutil=/hwrf/noscrub/soft/modulefiles
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics
module use $stutil
module load ruby emc-utils

#==========================================
# Submit several nam_smartinit domain runs
# calls RUN_ALL which submits each RUNTYP domain JNAM_SMINIT job
# Viable RUNTYP=conus,conusnest2p5,ak,ak_rtmages,aknest3,hi,pr,guam
# Jeff McQueen
#==========================================

# set job directory needed if running from cron
rootd=/meso/save/$USER/smart-dev
export jobd=${rootd}/jobs
#CTL ln -fs ${rootd}/ush/nam_smartinit.sh-ctl ${rootd}/ush/nam_smartinit.sh
ln -fs ${rootd}/ush/nam_smartinit.sh-cfg ${rootd}/ush/nam_smartinit.sh

cd $jobd

# Determine cycle
let HH=`date +%H`
if [ $HH -ge 01 -a $HH -le 06 ];then export cyc=00;
elif [ $HH -le 12 ];then export cyc=06;
elif [ $HH -le 18 ];then export cyc=12;
else 
  export cyc=18
fi 
 export cyc=12 #TEST

export fhrstr=00
export ENDHRS=12
echo DRIVER smartinit run from fhr $fhrstr to $ENDHRS

#07/13: change to run ak and alaskanest separately for good output listing
#07/13: added guam=guamnmm  configuration
#07/13: changed so 00 hr comes from parent nam for conus,ak,hi,pr (ecf scripts file)

for RUNTYP in conus ak hi pr ak_rtmages conusnest2p5 aknest3 guam;do
# for RUNTYP in aknest3 ;do
  export mdl=nam
  if [ $RUNTYP = guam ];then export mdl=hiresw;fi
  export NET=$mdl

  export RUNTYP=$RUNTYP

# Remove older directories
#  /nwprod/util/ush/setpdy.sh
  dayrm=$( echo `/nwprod/util/exec/ndate -120` |cut -c 1-8 )

  Y=$(echo $PDY | cut  -c 1-4 )
  M=$(echo $PDY | cut  -c 5-6 )
  D=$(echo $PDY | cut  -c 7-8 )
  wdayd=$Y$M$D
  rm -rf /ptmp/${USER}/${RUNTYP}/nam.${wdayd}

# Create and submit JNAM_SMINIT job

  echo SUBMIT RUN_ALL $RUNTYP  CYC $cyc
  $jobd/RUN_ALL >/stmp/$USER/smart-dev/smout-${RUNTYP} 2>&1 &
  sleep 10
done
