#!/bin/ksh
####NCO set -xa   #NCO preferred setting

########################################
# NAM SMARTINIT JOB   
########################################

################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Job name:         J{MDL}_SMINIT
# Job description:  Run dgex smartinit jobs
#
# Author:        Bradley Mabe       Org: NP11         Date: 2007-08-23
#
# Abstract: This script runs the Nam  Smart Init jobs
#
# Script history log:
# 2007-08-23  Bradley Mabe  - Created script (copied actually) to call nam_smartinit on & off
#                          initially of Alaskan precip & snowfall
# 2007-09-17  Geoff Manikin - This version for CONUS runs
# 2011-07-06  Geoff Manikin - Adapted to use nested output
# 2011-07-22  Geoff Manikin - Can't use nest output for F00
# 2012-12-03  Jeff McQueen  - Adapted for unified smartinit
# 2013-08-27  Jeff McQueen  - Put in vertical structure     

#  NOTE: cyc, ffhr, RUNTYP must be set from controlling ECFlow script
#   export cyc = 00,06,12,18
#   export ffhr = 00,03,06...84
#   export RUNTYP = conus,conunest2p5, ak,aknest3, hi, pr

#Changed to modeld to smartinit to accomodate other models COM)IN dir by using NET
export modeld=${modeld:-smartinit}  #Changed to smartinit to accomodate other models with NET

echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo modeld is ${modeld:?}
echo model_ver is ${model_ver:?}

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ECF script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
#NCO set NET = nam, dgex or hiresw for GUAM run
export NET=${NET:-dgex}
export RUN=${RUN:-dgex}
export GUESS=${GUESS:-NAM} # Indicates whether a NAM NDAS or NAM coldstart (GDAS) initial condition (08/2013)
export mdl=${mdl:-dgex}   # Delineates parent model (nam, hiresw,rap,gfs..>)

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}

#  NOW SET IN : parm/smart_para_config
#               which is called from kick_scripts/DRIVER and RUN_ALL
#####################################################################################


###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod ];then
 if [ "$envir" != prod ]; then
   export SENDDBN=${SENDDBN:-NO}
   export SENDDBN_GB2=${SENDDBN_GB2:-YES}   #NCO preference
   export pcom=${pcom:-/pcom/${envir}/${NET}}
 fi
else
 dng_para_config${RUNTYP}   #EMC User set
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd}
export DATA=${DATA:-$DATA_IN/${job}.${pid}}
#NCO export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
if [ "$envir" = 'prod' ] ; then
  export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.$$}
else
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
fi

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDDBN_GB2=${SENDDBN_GB2:-YES}

####################################
# Specify Execution Areas
# dng = downscaled gridding
####################################
export ROOTdng=${ROOTdng:-/nwprod}  # or /meso/save/${USER}
export HOMEdng=${HOMEdng:-/nw${envir}/${modeld}.$model_ver}  # NCO preferred

export EXECdng=${EXECdng:-${HOMEdng}/exec}
export EXECnam=${EXECnam:-${ROOTdng}/exec}   #Point to nam_prdgen until nam is in vert structure
export EXECdgex=${EXECdgex:-${ROOTdng}/exec}   #Point to dgex_prdgen until dgex is in vert structure
 export FIXdng=${FIXdng:-${HOMEdng}/fix}
export PARMdng=${PARMdng:-${HOMEdng}/parm}
 export USHdng=${USHdng:-${HOMEdng}/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}
export utilparm=${utilparm:-/nwprod/util/parm}
export gespath=${gespath:-/nwges/prod}

###############################################################
# Run setup to initialize working directory and utility scripts
###############################################################
sh $utilscript/setup.sh

###########################################
# Run setpdy and initialize PDY variables
###########################################
sh $utilscript/setpdy.sh  
. ${DATA}/PDY    # set local dir for crontab
#TEST export PDY=20140227  #TEST###########################

# Set GUESS, CYCLE parameters from NAM run 
sh  ${gespath}/${RUN}.${PDY}/${RUN}.t${cyc}z.envir.sh 
#   For testing cold start export GUESS=GDAS   #TEST

##############################################
# Define COM directories
# USER DEFINES in parm/dng_para_config
##############################################
export COMROOT=${COMROOT:-/com}    #location of DATE file
export COM_IN=${COM_IN:-/com/${NET}/prod}
export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}

export COMIN=$COM_IN/${RUN}.${PDY}
export COMOUT=$COM_OUT/${RUN}.${PDY}

mkdir -p $COMOUT
cp ${PARMdng}/SMINIT.CTL $DATA

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc

export gefscyc
let gefscyc2=$gefscyc

if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COM_SREF=${COM_SREF:-/com/sref/prod}
export COMIN_SREF=$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod
export COMIN_GEFS=$COM_SREF/sref.${GEFS_PDY}/ensprod_gefs

export pcom=${pcom:-/pcom/${NET}}
mkdir -p $pcom

####NCO SET env  

msg="JOB $job HAS BEGUN"
./postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
${NAM_SMINIT_CONUSSH:-$HOMEdng/scripts/ex${NET}_${modeld}.sh.ecf}
########################################################
cat $pgmout

msg="ENDED NORMALLY."
./postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date

