#!/bin/ksh
####NCO set -xa   #NCO preferred setting
#BSUB -L /bin/sh
#BSUB -P GFS-MTN
#BSUB -network type=sn_all:mode=US
#BSUB -oo gfs_sminit.out.%J 
#BSUB -eo gfs_sminit.out.%J
#BSUB -J sminitguam_test      
#BSUB -q dev
#BSUB -W 00:15 
#BSUB -n 64 
#BSUB -R span[ptile=8]
#BSUB -R affinity[core(2)]
#BSUB -x
#BSUB -a poe
set -xa
export OMP_NUM_THREADS=2
export MP_EUIDEVELOP=min
export KMP_STACKSIZE=2048m
export MPICH_ALLTOALL_THROTTLE=0
export MP_SINGLE_THREAD=yes
export MP_EAGER_LIMIT=65536
export MP_USE_BULK_XFER=no
export MP_COLLECTIVE_OFFLOAD=no
export MP_SHARED_MEMORY=yes
export MP_MPILIB=mpich2
export MP_LABELIO=yes
########################################
# GFS SMARTINIT JOB   
########################################

################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Job name:         gfs_smartinit.job
# Job description:  Run gfs smartinit jobs
#
# Author:        Bradley Mabe       Org: NP11         Date: 2007-08-23
#
# Abstract: This script runs the GFS Smart Init jobs
#
# Script history log:
# 2007-08-23  Bradley Mabe  - Created script (copied actually) to call nam_smartinit on & off
#                          initially of Alaskan precip & snowfall
# 2013-08-27  Jeff McQueen  - Put in vertical structure     
# 2014-03-01  DaNa Carlis   - Adapted for GFS to unify NAM and GFS DNG

#Changed to modeld to smartinit to accomodate other models COM)IN dir by using NET
export modeld=${modeld:-smartinit}  #Changed to smartinit to accomodate other models with NET
cyc=00
envir=prod
model_ver=gfs
RUNTYP=guamnest
echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo modeld is ${modeld:?}
echo model_ver is ${model_ver:?}

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ECF script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}

#export SENDECF=${SENDECF:-YES}
export SENDECF=${SENDECF:-NO}

if [ $envir = "prod" ]
then
  export SENDDBN_GB2=YES
  export SENDDBN_NTC=YES
  export DBN_ALERT_TYPE1=SMARTGUAM # used in ush script
  export DBN_ALERT_TYPE2=GFS_SMARTGUAM_GB2 # used in ush script
  export jlogfile=/com/logs/jlogfiles/jlogfile.${job}.$$
else
  export SENDDBN_GB2=NO
  export SENDDBN_NTC=NO # Don't set to yes with script in para or test
  export DBN_ALERT_TYPE1=SMARTGUAM_PARA
  export DBN_ALERT_TYPE2=GFS_SMARTGUAM_GB2_PARA
  export jlogfile=/com/logs/${envir}/jlogfile
  export NET=gfs
  export RUN=gfs
  export pcom=/pcom/${envir}/${RUN}
fi

###################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-gfs}
export RUN=${RUN:-gfs}
export GUESS=${GUESS:-GFS}  
export mdl=${mdl:-gfs}  

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod ];then
 if [ "$envir" != prod ]; then
   export SENDDBN=${SENDDBN:-NO}
   export SENDDBN_GB2=${SENDDBN_GB2:-YES}   #NCO preference
   export pcom=${pcom:-/pcom/${envir}/${NET}}
 fi
else
 dng_para_config${RUNTYP}   #EMC User set
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
#export DATA_IN=${DATA_IN:-/tmpnwprd}
export DATA_IN=${DATA_IN:-/ptmpp1/$USER}
#export DATA=${DATA:-$DATA_IN/${job}.${pid}}
export DATA=${DATA:-$DATA_IN/gfsdng_new.${pid}}
#NCO export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA

export PDY=20140512
export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
if [ "$envir" = 'prod' ] ; then
  export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.$$}
else
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
fi

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-NO}
export SENDDBN=${SENDDBN:-NO}
export SENDDBN_GB2=${SENDDBN_GB2:-NO}

####################################
# Specify Execution Areas
# dng = downscaled gridding
####################################
export ROOTdng=${ROOTdng:-/nwprod}  # or /meso/save/${USER}
#export HOMEdng=${HOMEdng:-/nw${envir}/${modeld}.$model_ver}  # NCO preferred
#export HOMEdng=${HOMEdng:-/nw${envir}/nam_smartinit.v3.2.2}  # NCO preferred
export HOMEdng=${HOMEdng:-/global/save/Dana.Carlis/svn/smartinit/branches/EXP-gfs}  

export EXECdng=${EXECdng:-${HOMEdng}/exec}
export EXECnam=${EXECnam:-${ROOTdng}/exec}   #Point to nam_prdgen until nam is in vert structure
 export FIXdng=${FIXdng:-${HOMEdng}/fix}
export PARMdng=${PARMdng:-${HOMEdng}/parm}
 export USHdng=${USHdng:-${HOMEdng}/ush}

###################################
# Set up the UTILITIES
###################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}
export utilparm=${utilparm:-/nwprod/util/parm}
export gespath=${gespath:-/nwges/prod}

###############################################################
# Run setup to initialize working directory and utility scripts
###############################################################
#sh $utilscript/setup.sh

###########################################
# Run setpdy and initialize PDY variables
###########################################
sh $utilscript/setpdy.sh  
. ${DATA}/PDY    # set local dir for crontab
### export PDY=20140205   #TEST

# Set GUESS, CYCLE parameters from NAM run 
#sh  ${gespath}/${RUN}.${PDY}/${RUN}.t${cyc}z.envir.sh 
#   For testing cold start export GUESS=GDAS   #TEST

##############################################
# Define COM directories
# USER DEFINES in parm/dng_para_config
##############################################
export COMROOT=${COMROOT:-/com}    #location of DATE file
#export COM_IN=${COM_IN:-/com/${NET}/${envir}}
export COM_IN=${COM_IN:-/global/noscrub/Russ.Treadon/com/${NET}/para}
#export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}

export COMIN=$COM_IN/${RUN}.${PDY}
#export COMOUT=$COM_OUT/${RUN}.${PDY}
export COMOUT=$DATA

mkdir -p $COMOUT
cp ${PARMdng}/SMINIT.CTL $DATA

##############################################
# Set up the forecast hours
##############################################
export SHOUR=00
export EHOUR=192
export EHOUR_HRLY=12
export FHINC_HRLY=01
export FHINC=03

###############################################
# Specify Timeout Behavior of GFS DNG
#
# SLEEP_TIME - Amount of time to wait for
#              a input file before exiting
# SLEEP_INT  - Amount of time to wait between
#              checking for input files
###############################################
#export SLEEP_TIME=300
export SLEEP_TIME=30
export SLEEP_INT=10

####################################
# Check if this is a restart
####################################
if test -f $COMOUT/$RUN.t${cyc}z.control.smartguam
then
  modelrecvy=`cat < $COMOUT/${RUN}.t${cyc}z.control.smartguam`
  recvy_pdy=`echo $modelrecvy | cut -c1-8`
  recvy_cyc=`echo $modelrecvy | cut -c9-10`
  recvy_shour=`echo $modelrecvy | cut -c11-`
  if test $RERUN = "NO"
  then
    if [ $recvy_shour -lt $EHOUR_HRLY ]
      then
      NEW_SHOUR=`expr $recvy_shour + $FHINC_HRLY`
    else
      NEW_SHOUR=`expr $recvy_shour + $FHINC`
    fi
    if test $NEW_SHOUR -ge $SHOUR
    then
      export SHOUR=$NEW_SHOUR
      if [ $SHOUR -lt 10 ]; then SHOUR=0$SHOUR; fi
    fi
    if test $recvy_shour -ge $EHOUR
    then
      msg="GFS DNG GUAM Already Completed to $EHOUR"
      postmsg "$jlogfile" "$msg"
    else
      msg="Starting: PDY=$PDY cycle=t${recvy_cyc}z SHOUR=$SHOUR      ."
      postmsg "$jlogfile" "$msg"
    fi
  fi
fi

#let srefcyc=$cyc-3
#if [ $srefcyc -lt 0 ] ; then
#  let srefcyc=$srefcyc+24
#  export SREF_PDY=$PDYm1
#else
#  export SREF_PDY=$PDY
#fi

#let gefscyc=$cyc-6
#if [ $gefscyc -lt 0 ] ; then
#  let gefscyc=$gefscyc+24
#  export GEFS_PDY=$PDYm1
#else
#  export GEFS_PDY=$PDY
#fi

#export srefcyc
#let srefcyc2=$srefcyc
###typeset -Z2 srefcyc2

#export gefscyc
#let gefscyc2=$gefscyc
###typeset -Z2 gefscyc2

#DEV TEST typeset problem
#if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
#if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

#export COM_SREF=${COM_SREF:-/com/sref/prod}
#export COM_GEFS=${COM_GEFS:-/com/gens/prod}
#export COMIN_SREF=$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod
#export COMIN_GEFS=$COM_SREF/gefs.${GEFS_PDY}/${cyc}/


msg="JOB $job HAS BEGUN"
./postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
${GFS_SMINIT_GUAM:-$HOMEdng/scripts/ex${NET}_${modeld}.sh.ecf}
########################################################
cat $pgmout

msg="ENDED NORMALLY."
./postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
#rm -rf $DATA
date

