#!/bin/ksh
set -xa   #NCO preferred setting

########################################
# NAM SMARTINIT JOB   
########################################

################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Job name:         nam_smartinitconus.job
# Job description:  Run nam smartinit jobs
#
# Author:        Bradley Mabe       Org: NP11         Date: 2007-08-23
#
# Abstract: This script runs the Nam  Smart Init jobs
#
# Script history log:
# 2007-08-23  Bradley Mabe  - Created script (copied actually) to call nam_smartinit on & off
#                          initially of Alaskan precip & snowfall
# 2007-09-17  Geoff Manikin - This version for CONUS runs
# 2011-07-06  Geoff Manikin - Adapted to use nested output
# 2011-07-22  Geoff Manikin - Can't use nest output for F00
# 2012-12-03  Jeff McQueen  - Adapted for unified smartinit
# 2013-08-27  Jeff McQueen  - Put in vertical structure     
# 2016-02-12  Annette Gibbs - Added NCO phase 2 standards

#  NOTE: cyc, ffhr, RUNTYP must be set from controlling ECFlow script
#   export cyc = 00,06,12,18
#   export ffhr = 00,03,06...84
#   export RUNTYP = conus,conunest2p5, ak,aknest3, hi, pr

# TEMPORARY SWITCH for VADJUST wind terrain adjustment
export IVADJ=${IVADJ:-T}

#Changed to modeld to smartinit to accomodate other models COM)IN dir by using NET
export modeld=${modeld:-smartinit}  #Changed to smartinit to accomodate other models with NET

echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo modeld is ${modeld:?}
echo model_ver is ${nam_smartinit_ver:?}

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ECF script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
#NCO set NET = namrr, nam, dgex or hiresw for GUAM run
export NET=${NET:-namrr}
export RUN=${RUN:-namrr}
export GUESS=${GUESS:-NAMRR} # Indicates whether a NAM NDAS or NAM coldstart (GDAS) initial condition (08/2013)
export mdl=${mdl:-namrr}   # Delineates parent model (namrr,nam,hiresw,rap,gfs..>)
export KEEPDATA=${KEEPDATA:-NO}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd2
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}

#  NOW SET IN : parm/smart_para_config
#               which is called from kick_scripts/DRIVER and RUN_ALL
#####################################################################################


###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi  #Comment out FOR NCO
if [ "$RUN_ENVIR" != nco ];then
 dng_para_config${RUNTYP}   #EMC User set
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATAROOT=${DATAROOT:-/tmpnwprd_p2}
export DATA=${DATA:-$DATAROOT/${job}.${pid}}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-$COMROOTp1/logs/jlogfiles/jlogfile.${job}.$$}
if [ "$envir" != 'prod' ] ; then
  export jlogfile=${jlogfile:-$COMROOTp1/logs/${envir}/jlogfile}
fi

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Specify Execution Areas
# dng = downscaled gridding
####################################
export HOMEdng=${HOMEdng:-$NWROOT/${modeld}.${nam_smartinit_ver}}  # NCO preferred
export HOMEnam=${HOMEnam:-$NWROOTp1/nam.${nam_ver}}

export EXECdng=${EXECdng:-${HOMEdng}/exec}
export EXECnam=${EXECnam:-${HOMEnam}/exec}   #Point to nam_prdgen
export FIXdng=${FIXdng:-${HOMEdng}/fix}
export PARMdng=${PARMdng:-${HOMEdng}/parm}
export USHdng=${USHdng:-${HOMEdng}/ush}

###################################
# Set up the UTILITIES
###################################
#export utilscript=${utilscript:-/nwprod/util/ush}
#export utilexec=${utilexec:-/nwprod/util/exec}
#export utilparm=${utilparm:-/nwprod/util/parm}
#export gespath=${gespath:-/nwges/${envir}}
export GESIN=${GESIN:-$GESROOTp1/${envir}}

. /usrx/local/Modules/default/init/ksh
module load /nwpara2/modulefiles/util_shared/v1.0.3
module load grib_util

# use local versions of cnvgrib and wgrib2
#export WGRIB2=/meso/save/Eric.Rogers/utils/wgrib2_wesley_fornam/wgrib2new
export WGRIB2=${EXECdng}/smartinit_wgrib2
export CNVGRIB=${EXECdng}/smartinit_cnvgrib

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. PDY  # set local dir for crontab

# Set GUESS, CYCLE parameters from NAM run 
#   For testing cold start export GUESS=GDAS   #TEST
if [ -s $GESIN/${RUN}.${PDY}/${RUN}.t${cyc}z.envir.sh ];then
.  $GESIN/${RUN}.${PDY}/${RUN}.t${cyc}z.envir.sh
else
   echo  $GESIN/${RUN}.${PDY}/${RUN}.t${cyc}z.envir.sh NOT FOUND
   export GUESS=NDAS
fi
echo GUESS=$GUESS
export pcfhr=06
export pcdate=`$NDATE -${pcfhr} $PDY$cyc |cut -c 1-8`
export pcyc=`$NDATE -${pcfhr} $PDY$cyc |cut -c 9-10`


##############################################
# Define COM directories
# USER DEFINES in parm/dng_para_config
##############################################
export COM_IN=${COM_IN:-$COMROOTp1/${NET}/${envir}}
export COM_OUT=${COM_OUT:-$COMROOTp1/${NET}/${envir}}

export COMIN=$COM_IN/${RUN}.${PDY}
export COMOUT=$COM_OUT/${RUN}.${PDY}

mkdir -p $COMOUT
cp ${PARMdng}/SMINIT.CTL $DATA

let srefcyc=$cyc-3
if [ $srefcyc -lt 0 ] ; then
  let srefcyc=$srefcyc+24
  export SREF_PDY=$PDYm1
else
  export SREF_PDY=$PDY
fi

let gefscyc=$cyc-6
if [ $gefscyc -lt 0 ] ; then
  let gefscyc=$gefscyc+24
  export GEFS_PDY=$PDYm1
else
  export GEFS_PDY=$PDY
fi

export srefcyc
let srefcyc2=$srefcyc
###typeset -Z2 srefcyc2

export gefscyc
let gefscyc2=$gefscyc
###typeset -Z2 gefscyc2

#DEV TEST typeset problem
if [ $srefcyc2 -lt 10 ];then srefcyc2="0"${srefcyc2};fi
if [ $gefscyc2 -lt 10 ];then gefscyc2="0"${gefscyc2};fi

export COM_SREF=${COM_SREF:-/com2/sref/prod}
export COMIN_SREF=$COM_SREF/sref.${SREF_PDY}/${srefcyc2}/ensprod
export COMIN_GEFS=$COM_SREF/sref.${GEFS_PDY}/ensprod_gefs

export PCOM=${PCOM:-$PCOMROOT/${NET}}
mkdir -p $PCOM

####NCO-SET env  

msg="JOB $job HAS BEGUN"
postmsg "$jlogfile" "$msg"

########################################################
# Execute the script.
${NAM_SMINIT_CONUSSH:-$HOMEdng/scripts/ex${NET}_${modeld}.sh.ecf}
########################################################
cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATAROOT
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi

date

