#!/bin/sh
set -xa

########################################
# NAM SMARTINIT 
########################################

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ecf script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-prod}
export SENDECF=${SENDECF:-YES}

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = prod -a $envir != prod ]; then
  export DBNROOT=/nwprod/spa_util/para_dbn
  export pcom=${pcom:-/pcom/${envir}/nam}
  export jlogfile=${jlogfile:-/com/logs/${envir}/jlogfile}
fi

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd2
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" != prod ]      ### For Developers, "group_name" is passed from the ECF script
then
  group_name=${group_name:-meso}
  package_name=${package_name:-nam}
  . /${group_name}/save/${LOGNAME}/${package_name}/nwprod/parm/${package_name}_para_config
  export userid=${userid:-$LOGNAME}
  export DATA_IN=${DATA_IN:-/ptmpp1/$userid}
fi

export PS4='$SECONDS + '
date

####################################
# obtain unique process id (pid) and make temp directory
####################################
export pid=$$
export DATA_IN=${DATA_IN:-/tmpnwprd2}
export DATA=$DATA_IN/${job}.${pid}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-/com/logs/jlogfiles/jlogfile.${job}.$$}

####################################
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy files to /com directory
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

#
# Set up model and cycle specific variables
#
GRID=`echo $grid |tr '[a-z]' '[A-Z]'`
export NET=${NET:-nam}
export RUN=${RUN:-smart${grid}}
export model=${model:-nam}
export GRIB=smart${grid}
export EXT=tm00
export DBN_ALERT_TYPE=SMART${GRID}_GEMPAK

if [ $RUN = smartconus2p5 -o $RUN = smartak3 ]; then
  export fend=60 
else
  export fend=84 
fi
export finc=3
export fstart=3

#
# Now set up GEMPAK/NTRANS environment
#
. /nwprod/gempak/.gempak

###################################
# Set up the UTILITIES
##################################
export utilscript=${utilscript:-/nwprod/util/ush}
export utilexec=${utilexec:-/nwprod/util/exec}
export utilities=${utilities:-/nwprod/util/ush}

export HOMEscripts=${HOMEscripts:-/nw${envir}/nam_smartinit.${model_ver}/scripts}

# Run setup to initialize working directory and utility scripts
sh $utilscript/setup.sh
# Run setpdy and initialize PDY variables
sh $utilscript/setpdy.sh
. PDY

##############################################
# Define COM directories
##############################################
export COM_IN=/com/${NET}/${envir} #XXW
export COM_IN=${COM_IN:-/com/${NET}/prod}
export COM_OUT=${COM_OUT:-/com/${NET}/${envir}}
export COM_AWP=${COM_AWP:-/com/nawips/${envir}}

export com=${com:-$COM_OUT}
export COMIN=$COM_IN/nam.${PDY}
export COMOUT=$COM_AWP/${RUN}.${PDY}

if [ ! -f $COMOUT ] ; then
  mkdir -p -m 775 $COMOUT
fi
 
env

${HOMEscripts}/exnawips_nam_smartinit.sh.ecf

#################################################################

cat $pgmout

msg="ENDED NORMALLY."
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
cd $DATA_IN
if [ ${RM_TMPDIR:-YES} = YES ] ; then rm -rf $DATA ; fi

date
