#!/bin/ksh
set -xa   #NCO preferred setting

########################################
# NAM SMARTINIT JOB   
########################################

################################################################################
####  UNIX Script Documentation Block
#                      .                                             .
# Job name:         nam_smartinitconus.job
# Job description:  Run nam smartinit jobs
#
# Author:        Bradley Mabe       Org: NP11         Date: 2007-08-23
#
# Abstract: This script runs the Nam  Smart Init jobs
#
# Script history log:
# 2007-08-23  Bradley Mabe  - Created script (copied actually) to call nam_smartinit on & off
#                          initially of Alaskan precip & snowfall
# 2007-09-17  Geoff Manikin - This version for CONUS runs
# 2011-07-06  Geoff Manikin - Adapted to use nested output
# 2011-07-22  Geoff Manikin - Can't use nest output for F00
# 2012-12-03  Jeff McQueen  - Adapted for unified smartinit
# 2013-08-27  Jeff McQueen  - Put in vertical structure     
# 2016-02-12  Annette Gibbs - Added NCO phase 2 standards
# 2025-07-18  Annette Gibbs - Replaced NAM/NAM nest with RRFSv1

#  NOTE: cyc, ffhr, RUNTYP must be set from controlling ECFlow script
#   export cyc = 00,06,12,18
#   export ffhr = 00,03,06...84
#   export RUNTYP = conus,conunest2p5, ak,aknest3, hi, pr

# TEMPORARY SWITCH for VADJUST wind terrain adjustment
# TEMPORARY SWITCH for DIVMIN nondivergent wind adjustment (IDMADJ - Calmet Method)
# TEMPORARY SWITCH for WNDADJ nondivergent wind adjustment (IWOXADJ - WOX Method)
export IVADJ=${IVADJ:-T}
export IDMADJ=${IDMADJ:-F}
export IWOXADJ=${IWOXADJ:-F}

#Changed to modeld to smartinit to accomodate other models COM)IN dir by using NET
export modeld=${modeld:-smartinit}  #Changed to smartinit to accomodate other models with NET

echo cyc is ${cyc:?}
echo envir is ${envir:?}
echo modeld is ${modeld:?}
echo model_ver is ${smartinit_ver:?}

######################################################
# The following two variable could be defined in the
# loadleveler submission script (the ECF script), if
# not they will take the default values which is set
# for the NCO running enviroment
#######################################################
export RUN_ENVIR=${RUN_ENVIR:-nco}

export SENDECF=${SENDECF:-YES}

###################################
# Specify NET and RUN Name and model
####################################
#NCO set NET = nam, dgex or hiresw for GUAM run
export NET=${NET:-smartinit}
export RUN=${RUN:-rrfs}
export GUESS=${GUESS:-RRFS} # Indicates whether a NAM NDAS or NAM coldstart (GDAS) initial condition (08/2013)
export mdl=${mdl:-rrfs}   # Delineates parent model (nam, hiresw,rap,gfs..>)
export KEEPDATA=${KEEPDATA:-NO}

#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to /tmpnwprd2
# SENDECF: If the job is to be running using ECF, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}

#  NOW SET IN : parm/smart_para_config
#               which is called from kick_scripts/DRIVER and RUN_ALL
#####################################################################################


###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################

if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi  #Comment out FOR NCO

export PS4='+ $SECONDS + '
date

####################################
# make temp directory
####################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=t${cyc}z

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"

####################################
# Specify Execution Areas
# dng = downscaled gridding
####################################
export HOMEdng=${HOMEsmartinit:-$PACKAGEROOT/${NET}.${smartinit_ver}}  # NCO preferred

export EXECdng=${EXECdng:-${HOMEdng}/exec}
export FIXdng=${FIXdng:-${HOMEdng}/fix}
export PARMdng=${PARMdng:-${HOMEdng}/parm}
export USHdng=${USHdng:-${HOMEdng}/ush}

###########################################
# Run setpdy and initialize PDY variables
###########################################
setpdy.sh
. ./PDY  # set local dir for crontab

##############################################
# Define COM directories
# USER DEFINES in parm/dng_para_config
##############################################

#export COM_INrrfs=${COM_INrrfs:-$(compath.py $envir/${RUN}/${rrfs_ver})}
export COMINrrfs=${COMINrrfs:-$(compath.py $envir/${RUN}/${rrfs_ver})/${RUN}.${PDY}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${smartinit_ver})/${RUN}.${PDY}}

export COMOUTwmo=${COMOUTwmo:-${COMOUT}/wmo}

mkdir -p $COMOUT $COMOUTwmo
#cp ${PARMdng}/SMINIT.CTL $DATA

msg="JOB $job HAS BEGUN"
postmsg "$msg"

env

########################################################
# Execute the script.
$HOMEdng/scripts/ex${NET}.sh
export err=$?; err_chk
########################################################

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

msg="ENDED NORMALLY."
postmsg "$msg"

##############################
# Remove the Temporary working directory
##############################
if [ ${KEEPDATA:-NO} = NO ] ; then rm -rf $DATA ; fi
#if [ "${KEEPDATA^^}" != YES ]; then
#   rm -rf $DATA
#fi

date

