#!/bin/ksh
#=======================================================
# Driving script to run all plot metjobs
# calls plotmet.job, plotdiff.job, ftpmet.job
# Jeff McQueen   01/29/2013
#=======================================================
. /usrx/local/Modules/3.2.9/init/ksh
module load ibmpe lsf ics

#set -x 
typeset -Z2 cyc ffhr

export iftp=1
#TEST export ymd=20130709  #TEST
export ymd=`/nwprod/util/exec/ndate |cut -c 1-8`
export cyc=12     
export pltcfg=smart    #cfg varbs to plt : smart,nam,nam2,nmm,test
export nplts=10 # number of varbs to plot 
export nftp=4 # number of ftps while job is running sep by slpftp (eg: 30 mins)

export strhr=00           # Starting forecast hour
export ENDHRS=12          # Ending forecast hour
export INCR=03            # Forecast hour increment

export domains="conus ak hi pr"
set -A mdl smart nam      #GRIB model file type (smart, nam...)

# grib dir :  /com/${mdld}/prod/${mdl}.${ymd} (/com/nam/prod/nam.20130715
# mdl file :  ${mdld}.t00z.smart{REGION}{fhr}.tm00 (nam.t12z.smarthi03.tm00)

export scrdir=/meso/save/$USER/gempak/sfcplot/smart

((nplfcst=(ENDHRS-strhr)/INCR + 1))
((slpdiff=45*nplfcst))
((slpftp=30*nplfcst*(nplts-1)))

# reg for nam    : conus/conusnest alaskanest  hawaiinest priconest            gfs
# reg for sminit : conus/conus2p5  ak/aknest3  hi         pr        ak_rtmages guam

for PTYP in met diff;do
  for REGION in ${domains}; do

    export mdld="nam nam" 
    case $REGION in 
      conus|conusnest)  PAREA="dset nyc* gulf*";;
       guam)  PAREA=guam;export mdld="gfs hires";;
          *)  PAREA=dset;;
     esac

     for plotarea in ${PAREA};do 
       export plotarea
       parea=`echo $plotarea |cut -d* -f1`

#      Regions set for smartinit vs nam nest mdl comparisons
       if [ ${mdl[1]} = nam ];then
         case $REGION in 
           conus|conus2p5)  export reg="${REGION} conusnest";;
               ak|aknest3)  export reg="${REGION} alaskanest";;
                       hi)  export reg="${REGION} hawaiinest";;
                       pr)  export reg="${REGION} priconest";;
                        * ) export reg="$REGION $REGION";;
         esac
       else 
         export reg="$REGION $REGION"
       fi
       export mdl=${mdl[*]}
       export job="gemsm.${REGION}${parea}${cyc}"

       echo;echo `date`
       echo SUBMIT plot${PTYP}.job for  $REGION   GAREA $plotarea   CYCLE: $cyc Z from fhrs $strhr to $ENDHRS
       bsub < $scrdir/plot${PTYP}.job
       if [ $plotarea != dset ];then sleep $slpdiff;fi
     done
   done

  echo;echo Wait $slpdiff secs for  $REGION   GAREA $plotarea  CYCLE:  $cyc Z cycle gem files to be differenced
  echo `date`
  sleep $slpdiff
# ftp plots as they are created
  $scrdir/FTP_MET 
done

let jftp=1
export jftp
while [ $jftp -le $nftp ];do
   echo;echo Wait ${slpftp} secs for  CYCLE: $cyc Z cycle gem plots to be ftpd  $jftp
   sleep $slpftp
   echo `date`
   $scrdir/FTP_MET 
   ((jftp=jftp+1))
   export jftp
done

echo;echo `date`
echo RUN_GEM COMPLETED CYCLE $cyc   PLTCFG$pltcfg
