#!/bin/bash

set -x

date

COMMAND=$1

MODULEFILES=${MODULEFILES:-${HOMEsmartinit}/modulefiles}
versionfile=${versionfile:-${HOMEsmartinit}/versions/run.ver}

. /etc/profile
. /usr/share/lmod/lmod/init/sh >/dev/null # Module Support

. ${versionfile}


module purge
module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich/8.1.7
module load cray-pals/1.0.12
module load prod_util/2.0.9
module load prod_envir/2.0.4
module load libjpeg/9c
module load grib_util/1.2.2
module load wgrib2/2.0.8_wmo

module use /apps/ops/test/nco/modulefiles/core
module load rocoto

module list

export job=${job:-"${PBS_JOBNAME}"}    # job is defined as job name
export jid=`echo ${PBS_JOBID} | cut -f1 -d.`  # removal of tailing sub-server string
export jobid=${jobid:-"${job}.${jid}"}
echo " number of cores : $np for job $job with id as $jobid "

$COMMAND
