       PROGRAM ADDPRECIP12
C                .      .    .                                       .
C SUBPROGRAM:    ADDPRECIP12
C   PRGMMR: MANIKIN        ORG: W/NP22     DATE:  07-03-07
C
C ABSTRACT: PRODUCES 12-HOUR TOTAL AND CONVECTIVE PRECIPITATION BUCKETS
C              AS WELL AS SNOWFALL ON THE ETA NATIVE GRID FOR SMARTINIT 
C
C PROGRAM HISTORY LOG:
C   07-03-07  GEOFF MANIKIN 
C
C REMARKS:

C ATTRIBUTES:
C   LANGUAGE: FORTRAN-90
C   MACHINE:  CRAY C-90
C$$$
      INCLUDE "parmnam"
      PARAMETER(ITOT=ILIM*JLIM)
      DIMENSION GRID(ITOT),DIFF(5)
      DIMENSION INCDAT(8),JNCDAT(8)
      INTEGER JPDS(200),JGDS(200),KPDS(200),KGDS(200)
      INTEGER LEVS(MAXLEV),IVAR(5)
      INTEGER FHR1, FHR2, FHR3, FHR4, FHR0
      LOGICAL*1 MASK(ITOT), MASK2(ITOT)
C
      PARAMETER(MBUF=2000000,JF=1000000)
      CHARACTER CBUF(MBUF)
      CHARACTER CBUF2(MBUF)
      CHARACTER*11 ENVVAR
      CHARACTER*80 FNAME
      LOGICAL*1 LB(JF)
      REAL F(JF)
      PARAMETER(MSK1=32000,MSK2=4000)
      INTEGER JENS(200),KENS(200)
      DIMENSION APCP1(ITOT),APCP2(ITOT),APCP3(ITOT),
     &     APCP4(ITOT),APCP12HR(ITOT)
      DIMENSION CAPCP1(ITOT),CAPCP2(ITOT),CAPCP3(ITOT),
     &     CAPCP4(ITOT),CAPCP12HR(ITOT)
      DIMENSION SNOW1(ITOT),SNOW2(ITOT),SNOW3(ITOT),
     &     SNOW4(ITOT),SNOW12HR(ITOT)

C
      READ (5,*) FHR1, FHR2, FHR3, FHR4
      print *, 'fhr1 fhr2 fhr3 fhr4 ', FHR1, FHR2, FHR3, FHR4
      FHR0=FHR1-3
      NUMLEV=MAXLEV
C
      LUGB=13
      LUGI=14
      LUGB2=15
      LUGI2=16
      LUGB3=17
      LUGI3=18
      LUGB4=19
      LUGI4=20
      LUGB5=50
      LUGB6=51
      LUGB7=52
C
      JJ1 = 1
      JJINC = 1
C
      ISTAT = 0
C
C  READ INDEX FILE TO GET GRID SPECS 
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      ENVVAR='XLFUNIT_   '
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB,FNAME,IRETGB)
      ENVVAR='XLFUNIT_   '
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGI
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGI,FNAME,IRETGI)
      CALL GETGI(LUGI,KSKIP,MBUF,CBUF,NLEN,NNUM,IRGI)
      write(6,*)' IRET FROM GETGI ',IRGI
      IF(IRGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        RETURN
      ENDIF 
c      REWIND LUGI

C
      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1
        JGDS = -1
        CALL GETGB1S(CBUF,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S FILE 1',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON 1ST READ OF GRIB FILE SO ABORT'
          ISTAT = IRGS
          RETURN
        ENDIF 
C
      ENDDO

C    GET GRID NUMBER FROM PDS
C
      IGDNUM = KPDS(3)
C
C   PROCESS THE GRIB FILE
C
      IMAX = KGDS(2)
      JMAX = KGDS(3)
      NUMVAL = IMAX*JMAX
      KMAX = MAXLEV
      WRITE(6,280) IMAX,JMAX,NUMLEV,KMAX
  280 FORMAT(' IMAX,JMAX,NUMLEV,KMAX ',5I4)
  285 FORMAT(' IV, IVAR, L, IRET:  ',4I5)

C -== GET SURFACE FIELDS ==-
      L = 0
      IV= 0

C   PRECIP 

c   to start each new file with its index, set J=-1 for sfc pressure
C
      J = 0 
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 061
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB,LUGI,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          APCP1(KK) = GRID(KK) 
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK PRECIP IN 1ST FILE ' 
         ISTAT = IRET
        RETURN
      ENDIF

C   PRECIP

C  CONVECTIVE PRECIP
      J = 0
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB,LUGI,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK,GRID,IRET)

      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CAPCP1(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CNVCT PRECIP IN 1ST FILE'
         ISTAT = IRET
        RETURN
      ENDIF

C  SNOWFALL 
      J = 0
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 065
      JPDS(6) = 001
      JPDS(14) = FHR0
      JPDS(15) = FHR1

      CALL GETGB(LUGB,LUGI,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SNOW1(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK SNOW IN 1ST FILE' 
         ISTAT = IRET
        RETURN
      ENDIF

C  PRINT VALUES AT POINT IN MIDDLE OF GRID

C BEGIN WORK ON 2ND FILE
      JJ1 = 1
      JJINC = 1

C  READ INDEX FILE TO GET GRID SPECS
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB2
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB2,FNAME,IRETGB2)
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGI2
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGI2,FNAME,IRETGI2)
      CALL GETGI(LUGI2,KSKIP,MBUF,CBUF2,NLEN,NNUM,IRGI)
      IF(IRGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        RETURN
      ENDIF
c      REWIND LUGI2

      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1 
        JGDS = -1
        CALL GETGB1S(CBUF2,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S FILE 2',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON 1ST READ OF GRIB FILE SO ABORT'
          ISTAT = IRGS
          RETURN
        ENDIF
C
      ENDDO

C   ACCUMULATED PRECIP 

      L = 0
      IV= 0
c   to start each new file with its index, set J=-1 for sfc pressure
C
C
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 061
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB2,LUGI2,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          APCP2(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK PCP 2ND GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C   ACCUMULATED CONVECTIVE PRECIP
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB2,LUGI2,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CAPCP2(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CPCP 2ND GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C   SNOWFALL
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 065
      JPDS(6) = 001
      JPDS(14) = FHR1
      JPDS(15) = FHR2
      CALL GETGB(LUGB2,LUGI2,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SNOW2(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK SNOW 2ND GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C BEGIN WORK ON 3RD FILE
      JJ1 = 1
      JJINC = 1

C  READ INDEX FILE TO GET GRID SPECS
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB3
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB3,FNAME,IRETGB3)
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGI3
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGI3,FNAME,IRETGI3)
      CALL GETGI(LUGI3,KSKIP,MBUF,CBUF2,NLEN,NNUM,IRGI)
      IF(IRGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        RETURN
      ENDIF

      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1
        JGDS = -1
        CALL GETGB1S(CBUF2,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S FILE 3',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON 1ST READ OF GRIB FILE SO ABORT'
          ISTAT = IRGS
          RETURN
        ENDIF
      ENDDO

C   ACCUMULATED PRECIP


      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 033
      JPDS(13) = 1
      CALL GETGB(LUGB3,LUGI3,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)

       WRITE(6,285)IV,JPDS(5),L,IRET,K

      J = -1
      JPDS = -1
c      JPDS(3) = IGDNUM
c      JPDS(5) = 061
c      JPDS(6) = 001
c      JPDS(13) = 1
      J=1
      CALL GETGB(LUGB3,LUGI3,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)

      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 061
      JPDS(6) = 001
      JPDS(13) = 1
c      J=1000
      CALL GETGB(LUGB3,LUGI3,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)

      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          APCP3(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK PCP 3RD GRID FILE '
         ISTAT = IRET
c        RETURN
      ENDIF

C   ACCUMULATED CONVECTIVE PRECIP
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB3,LUGI3,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CAPCP3(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CPCP 3RD GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C   SNOWFALL
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 065
      JPDS(6) = 001
      JPDS(14) = FHR2
      JPDS(15) = FHR3
      CALL GETGB(LUGB3,LUGI3,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SNOW3(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK SNOW 3RD GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C BEGIN WORK ON 4TH FILE
      JJ1 = 1
      JJINC = 1

C  READ INDEX FILE TO GET GRID SPECS
C
      IRGI = 1
      IRGS = 1
      KMAX = 0
      JR=0
      KSKIP = 0
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB4
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB4,FNAME,IRETGB4)
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGI4
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGI4,FNAME,IRETGI4)
      CALL GETGI(LUGI4,KSKIP,MBUF,CBUF2,NLEN,NNUM,IRGI)
      IF(IRGI .NE. 0) THEN
        WRITE(6,*)' PROBLEMS READING GRIB INDEX FILE SO ABORT'
        ISTAT = IRGI
        RETURN
      ENDIF

      DO K = 1, NNUM
        JR = K - 1
        JPDS = -1
        JGDS = -1
        CALL GETGB1S(CBUF2,NLEN,NNUM,JR,JPDS,JGDS,JENS,
     &               KR,KPDS,KGDS,KENS,LSKIP,LGRIB,IRGS)
        write(6,*)' IRET FROM GETGB1S FILE 4',IRGS
        IF(IRGI .NE. 0) THEN
          WRITE(6,*)' PROBLEMS ON 1ST READ OF GRIB FILE SO ABORT'
          ISTAT = IRGS
          RETURN
        ENDIF
      ENDDO

C   ACCUMULATED PRECIP

      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 061
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB4,LUGI4,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN 
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          APCP4(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),IRET
        WRITE(6,*)' COULD NOT UNPACK PCP 4TH GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C   ACCUMULATED CONVECTIVE PRECIP
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 063
      JPDS(6) = 001
      JPDS(13) = 1
      CALL GETGB(LUGB4,LUGI4,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          CAPCP4(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK CPCP 4TH GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

C   SNOWFALL
      J = -1
      JPDS = -1
      JPDS(3) = IGDNUM
      JPDS(5) = 065
      JPDS(6) = 001
      JPDS(14) = FHR3
      JPDS(15) = FHR4
      CALL GETGB(LUGB4,LUGI4,NUMVAL,J,JPDS,JGDS,KF,K,
     X           KPDS,KGDS,MASK2,GRID,IRET)
      IF(IRET.EQ.0) THEN
        II = 1
        JJ = JJ1
        DO KK = 1, ITOT
          SNOW4(KK) = GRID(KK)
        ENDDO
      ELSE
        WRITE(6,285)IV,JPDS(5),L,IRET
        WRITE(6,*)' COULD NOT UNPACK SNOW 4TH GRID FILE '
         ISTAT = IRET
        RETURN
      ENDIF

       DO K = 1, ITOT
          APCP12HR(K)=APCP1(K)+APCP2(K)+APCP3(K)+APCP4(K)
          CAPCP12HR(K)=CAPCP1(K)+CAPCP2(K)+CAPCP3(K)+CAPCP4(K)
          SNOW12HR(K)=SNOW1(K)+SNOW2(K)+SNOW3(K)+SNOW4(K)
       ENDDO

      KPDS(5)=61
      KPDS(14)=FHR0
      KPDS(15)=FHR4
      ENVVAR='XLFUNIT_   '
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB5
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB5,FNAME,IRET)
      CALL PUTGB(LUGB5,ITOT,KPDS,KGDS,MASK2,APCP12HR,IRET)
      CALL BACLOSE(LUGB5,IRET)

      KPDS(5)=63
      KPDS(14)=FHR0
      KPDS(15)=FHR4
      ENVVAR='XLFUNIT_   '
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB6
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB6,FNAME,IRET)
      CALL PUTGB(LUGB6,ITOT,KPDS,KGDS,MASK2,CAPCP12HR,IRET)
      CALL BACLOSE(LUGB6,IRET)

      KPDS(5)=65
      KPDS(14)=FHR0
      KPDS(15)=FHR4
      ENVVAR='XLFUNIT_   '
      WRITE(ENVVAR(9:10),FMT='(I2)') LUGB7
      CALL GETENV(ENVVAR,FNAME)
      CALL BAOPEN(LUGB7,FNAME,IRET)
      CALL PUTGB(LUGB7,ITOT,KPDS,KGDS,MASK2,SNOW12HR,IRET)
      CALL BACLOSE(LUGB7,IRET)
      STOP
      END
