setenv("smartinit_ver","v4.5.0")

local PrgEnv_intel_ver = os.getenv("PrgEnv_intel_ver")
local intel_ver = os.getenv("intel_ver")
local craype_ver = os.getenv("craype_ver")
local cray_mpich_ver = os.getenv("cray_mpich_ver")
local ip_ver = os.getenv("ip_ver")
local bacio_ver = os.getenv("bacio_ver")
local w3nco_ver = os.getenv("w3nco_ver")
local w3emc_ver = os.getenv("w3emc_ver")
local g2_ver = os.getenv("g2_ver")
local g2tmpl_ver = os.getenv("g2tmpl_ver")
local jasper_ver = os.getenv("jasper_ver")
local libpng_ver = os.getenv("libpng_ver")
local zlib_ver = os.getenv("zlib_ver")
local cfp_ver = os.getenv("cfp_ver")

load("PrgEnv-intel/"..PrgEnv_intel_ver)
load("intel/"..intel_ver)
load("craype/"..craype_ver)
load("cray-mpich/"..cray_mpich_ver)
load("ip/"..ip_ver)
load("bacio/"..bacio_ver)
load("w3nco/"..w3nco_ver)
load("w3emc/"..w3emc_ver)
load("g2/"..g2_ver)
load("g2tmpl/"..g2tmpl_ver)
load("jasper/"..jasper_ver)
load("libpng/"..libpng_ver)
load("zlib/"..zlib_ver)
load("cfp/"..cfp_ver)
